import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { expect, it, vi } from 'vitest';
import { CitationCard } from './CitationCard';

const citation={citation_id:'S3',source_filename:'product manual.pdf',page_start:4,page_end:4,chunk_id:'x',excerpt:'Table 1 | Column 3'};
it('renders the unchanged source-PDF action and source hierarchy',()=>{render(<CitationCard citation={citation}/>);const link=screen.getByRole('link',{name:/product manual.pdf.*page 4/i});expect(screen.getByText('Source S3')).toBeInTheDocument();expect(screen.getByText('Page 4')).toBeInTheDocument();expect(link).toHaveTextContent('Open source PDF');expect(link).toHaveAttribute('href','#open-source-pdf');expect(link).toHaveAttribute('target','_blank');expect(link).toHaveAttribute('rel','noopener noreferrer')});
it('connects the evidence toggle to the expanded source region without exposing internal IDs',async()=>{render(<CitationCard citation={{...citation,chunk_id:'private-chunk-hash'}}/>);const user=userEvent.setup();const toggle=screen.getByRole('button',{name:/view evidence/i});expect(toggle).toHaveAttribute('aria-expanded','false');const regionId=toggle.getAttribute('aria-controls');await user.click(toggle);expect(toggle).toHaveAttribute('aria-expanded','true');expect(screen.getByRole('region',{name:'Extracted source text'})).toHaveAttribute('id',regionId);expect(screen.getByText('Extracted source text')).toBeInTheDocument();expect(screen.getByText(citation.excerpt)).toBeInTheDocument();expect(screen.queryByText('Technical details')).toBeNull();expect(document.body).not.toHaveTextContent('private-chunk-hash')});
it('opens a named source without an invalid page fragment when its page is absent',()=>{render(<CitationCard citation={{...citation,page_start:null,page_end:null}}/>);expect(screen.getByRole('link',{name:/product manual.pdf/i})).toHaveAttribute('href','#open-source-pdf')});
it('closes failed PDF opening behind a safe visible error',async()=>{const open=vi.spyOn(window,'open').mockReturnValue(null);render(<CitationCard citation={citation}/>);await userEvent.setup().click(screen.getByRole('link',{name:/open source pdf/i}));expect(await screen.findByRole('alert')).toHaveTextContent('Unable to open the source PDF. Please try again.');expect(screen.getByRole('alert')).not.toHaveTextContent('product manual.pdf');open.mockRestore()});
it('omits PDF action without filename and keeps raw evidence harmless text',async()=>{render(<CitationCard citation={{...citation,source_filename:null,page_start:null,page_end:null,excerpt:'<b>raw</b>'}}/>);expect(screen.queryByRole('link',{name:/open source pdf/i})).toBeNull();await userEvent.setup().click(screen.getByRole('button',{name:/view evidence/i}));expect(screen.getByText((_,node)=>node?.textContent==='<b>raw</b>')).toBeInTheDocument()});
