import { useEffect, useRef, useState, type FormEvent } from 'react';
import { useLanguage } from '../i18n/LanguageContext';
import { searchLaboratories } from '../services/api';
import type { LaboratoryResult, LaboratorySearchResponse } from '../types/catalogue';
import { SpeechInput } from './SpeechInput';
import type { Audience } from '../types/chat';

const LIMS_SEARCH = 'https://lims.bis.gov.in/home/search_is_number/';
const LIMS_LABS = 'https://lims.bis.gov.in/home/labs/';
const BIS_CARE = 'https://www.bis.gov.in/bis-apps/?lang=en';
const BIS_JEWELLERS = 'https://www.bis.gov.in/hallmarking-overview/jewellers-registration-scheme/?lang=en';
const BIS_CENTRES = 'https://www.bis.gov.in/hallmarking-overview/hallmarking-centre/?lang=en';
const BIS_COMPLAINTS = 'https://www.bis.gov.in/consumer-overview/online-complaint-registration/?lang=en';

const copy = {
  en: { labs:'Testing laboratories', labsLead:'Find a starting point, then confirm the current recognition, exact test scope and price in BIS LIMS before contacting a lab.', labSearch:'IS number, product, laboratory or location', labPlaceholder:'Try IS 4151, electric toys, Noida…', search:'Search checked records', snapshot:'Locally checked BIS LIMS snapshot · 30 Sep 2026 · 2 records, not a live or complete BIS directory', matches:'checked local matches', noMatch:'No checked local record matches. This does not mean BIS LIMS has no suitable lab.', scope:'Listed grade / type', validity:'Recognition validity shown by LIMS', fee:'Listed testing charge (excluding taxes)', feeCaution:'Charges and test coverage may vary. Confirm the exact edition, test facilities, exclusions, current recognition and quotation with BIS LIMS and the lab.', source:'Check this record in BIS LIMS ↗', officialSearch:'Search current IS scope and testing charges in BIS LIMS ↗', officialLabs:'Search the current BIS recognised-labs list ↗', priceMissing:'Price not published—check with lab/BIS LIMS', handoff:'The official search supports IS number, lab name and product/title filters. Refine the search there and inspect each result’s scope and charge breakup.', hallmark:'Hallmarking and HUID', hallmarkLead:'A BIS hallmark indicates that a precious-metal article has been marked under the BIS hallmarking system. The HUID is a six-character alphanumeric identifier on a hallmarked article.', huidLabel:'HUID printed on the article', huidPlaceholder:'Six letters or digits', check:'Check input format', invalid:'Enter exactly six letters or digits. This is only an input-format check.', formatOk:'The input has six letters or digits. Its authenticity has NOT been verified by BIS Bandhu.', noVerification:'BIS Bandhu does not verify HUID authenticity, jewellers, articles or hallmark status.', steps:'To check authenticity: open the official BIS Care app, choose “Verify HUID”, enter the code as printed on the article, and review the result in the app.', bisCare:'Open official BIS Care app information ↗', hallmarkSource:'Read official BIS hallmarking information ↗' },
  hi: { labs:'परीक्षण प्रयोगशालाएँ', labsLead:'प्रारंभिक जानकारी देखें, फिर प्रयोगशाला से संपर्क करने से पहले BIS LIMS में वर्तमान मान्यता, सटीक परीक्षण दायरा और मूल्य की पुष्टि करें।', labSearch:'IS नंबर, उत्पाद, प्रयोगशाला या स्थान', labPlaceholder:'जैसे IS 4151, बिजली के खिलौने, नोएडा…', search:'जाँचे गए रिकॉर्ड खोजें', snapshot:'स्थानीय BIS LIMS स्नैपशॉट · 30 सितम्बर 2026 · 2 रिकॉर्ड; पूर्ण या लाइव निर्देशिका नहीं', matches:'स्थानीय जाँचे गए परिणाम', noMatch:'कोई जाँचा गया स्थानीय रिकॉर्ड नहीं मिला। इसका अर्थ यह नहीं कि BIS LIMS में उपयुक्त प्रयोगशाला नहीं है।', scope:'सूचीबद्ध ग्रेड / प्रकार', validity:'LIMS में दिखाई गई मान्यता अवधि', fee:'सूचीबद्ध परीक्षण शुल्क (कर अलग)', feeCaution:'शुल्क और परीक्षण कवरेज बदल सकते हैं। BIS LIMS और प्रयोगशाला से संस्करण, परीक्षण सुविधाएँ, अपवाद, वर्तमान मान्यता और कीमत जाँचें।', source:'BIS LIMS में यह रिकॉर्ड देखें ↗', officialSearch:'BIS LIMS में वर्तमान IS दायरा और शुल्क खोजें ↗', officialLabs:'वर्तमान BIS मान्यता प्राप्त प्रयोगशालाएँ खोजें ↗', priceMissing:'कीमत प्रकाशित नहीं—प्रयोगशाला/BIS LIMS से पूछें', handoff:'आधिकारिक खोज IS नंबर, प्रयोगशाला नाम और उत्पाद/शीर्षक फ़िल्टर देती है। वहाँ खोज सुधारें और हर परिणाम का दायरा व शुल्क विवरण देखें।', hallmark:'हॉलमार्किंग और HUID', hallmarkLead:'BIS हॉलमार्क दर्शाता है कि बहुमूल्य धातु की वस्तु BIS हॉलमार्किंग प्रणाली में चिह्नित है। HUID हॉलमार्क वाली वस्तु पर छह अक्षरों या अंकों का पहचानकर्ता है।', huidLabel:'वस्तु पर लिखा HUID', huidPlaceholder:'छह अक्षर या अंक', check:'इनपुट प्रारूप जाँचें', invalid:'ठीक छह अक्षर या अंक लिखें। यह केवल इनपुट प्रारूप की जाँच है।', formatOk:'इनपुट में छह अक्षर या अंक हैं। BIS Bandhu ने इसकी प्रामाणिकता सत्यापित नहीं की है।', noVerification:'BIS Bandhu HUID, जौहरी, वस्तु या हॉलमार्क स्थिति सत्यापित नहीं करता।', steps:'प्रामाणिकता जाँचने के लिए आधिकारिक BIS Care ऐप खोलें, “Verify HUID” चुनें, वस्तु पर लिखा कोड दर्ज करें और ऐप में परिणाम देखें।', bisCare:'आधिकारिक BIS Care ऐप जानकारी खोलें ↗', hallmarkSource:'आधिकारिक BIS हॉलमार्किंग जानकारी पढ़ें ↗' },
  mr: { labs:'चाचणी प्रयोगशाळा', labsLead:'प्रारंभिक माहिती शोधा; प्रयोगशाळेशी संपर्क करण्यापूर्वी BIS LIMS मध्ये सध्याची मान्यता, नेमकी चाचणी व्याप्ती आणि किंमत तपासा.', labSearch:'IS क्रमांक, उत्पादन, प्रयोगशाळा किंवा ठिकाण', labPlaceholder:'उदा. IS 4151, विद्युत खेळणी, नोएडा…', search:'तपासलेल्या नोंदी शोधा', snapshot:'स्थानिक BIS LIMS स्नॅपशॉट · 30 सप्टेंबर 2026 · 2 नोंदी; संपूर्ण किंवा थेट यादी नाही', matches:'स्थानिक तपासलेले परिणाम', noMatch:'जुळणारी स्थानिक नोंद नाही. याचा अर्थ BIS LIMS मध्ये योग्य प्रयोगशाळा नाही असे नाही.', scope:'नोंदवलेला दर्जा / प्रकार', validity:'LIMS वरील मान्यता मुदत', fee:'नोंदवलेले चाचणी शुल्क (कर वगळून)', feeCaution:'शुल्क आणि चाचणी व्याप्ती बदलू शकते. नेमकी आवृत्ती, सुविधा, अपवाद, सध्याची मान्यता आणि किंमत BIS LIMS व प्रयोगशाळेकडून तपासा.', source:'BIS LIMS मधील ही नोंद तपासा ↗', officialSearch:'BIS LIMS मध्ये सध्याची IS व्याप्ती व शुल्क शोधा ↗', officialLabs:'सध्याची BIS मान्यताप्राप्त प्रयोगशाळा यादी शोधा ↗', priceMissing:'किंमत प्रसिद्ध नाही—प्रयोगशाळा/BIS LIMS कडे चौकशी करा', handoff:'अधिकृत शोधात IS क्रमांक, प्रयोगशाळा नाव आणि उत्पादन/शीर्षक फिल्टर आहेत. तिथे शोध सुधारून प्रत्येक निकालाची व्याप्ती व शुल्क तपासा.', hallmark:'हॉलमार्किंग आणि HUID', hallmarkLead:'BIS हॉलमार्क म्हणजे मौल्यवान धातूची वस्तू BIS हॉलमार्किंग व्यवस्थेनुसार चिन्हांकित आहे. HUID हा वस्तूवरील सहा अक्षरी-अंकी ओळख क्रमांक आहे.', huidLabel:'वस्तूवरील HUID', huidPlaceholder:'सहा अक्षरे किंवा अंक', check:'इनपुटचा नमुना तपासा', invalid:'नेमकी सहा अक्षरे किंवा अंक लिहा. ही फक्त इनपुटच्या नमुन्याची तपासणी आहे.', formatOk:'इनपुटमध्ये सहा अक्षरे किंवा अंक आहेत. BIS Bandhu ने त्याची अस्सलता तपासलेली नाही.', noVerification:'BIS Bandhu HUID, विक्रेता, वस्तू किंवा हॉलमार्क स्थिती सत्यापित करत नाही.', steps:'अस्सलता तपासण्यासाठी अधिकृत BIS Care अ‍ॅप उघडा, “Verify HUID” निवडा, वस्तूवरील कोड टाका आणि अ‍ॅपमधील निकाल पाहा.', bisCare:'अधिकृत BIS Care अ‍ॅपची माहिती उघडा ↗', hallmarkSource:'अधिकृत BIS हॉलमार्किंग माहिती वाचा ↗' },
  ta: { labs:'சோதனை ஆய்வகங்கள்', labsLead:'தொடக்கத் தகவலைத் தேடி, ஆய்வகத்தை அணுகுமுன் BIS LIMS-இல் தற்போதைய அங்கீகாரம், துல்லிய சோதனை வரம்பு, கட்டணத்தை உறுதிசெய்க.', labSearch:'IS எண், தயாரிப்பு, ஆய்வகம் அல்லது இடம்', labPlaceholder:'எ.கா. IS 4151, மின்சார பொம்மை, நொய்டா…', search:'சரிபார்த்த பதிவுகளைத் தேடுக', snapshot:'உள்ளூர் BIS LIMS பதிவு · 30 செப்டம்பர் 2026 · 2 பதிவுகள்; நேரடி அல்லது முழுப் பட்டியல் அல்ல', matches:'உள்ளூரில் சரிபார்த்த பொருத்தங்கள்', noMatch:'உள்ளூரில் பொருந்தும் பதிவு இல்லை. BIS LIMS-இல் பொருத்தமான ஆய்வகம் இல்லை என்று இதன் பொருள் அல்ல.', scope:'பட்டியலிடப்பட்ட தரம் / வகை', validity:'LIMS காட்டும் அங்கீகாரக் காலம்', fee:'பட்டியலிடப்பட்ட சோதனைக் கட்டணம் (வரி தவிர)', feeCaution:'கட்டணமும் சோதனை வரம்பும் மாறலாம். சரியான பதிப்பு, வசதி, விதிவிலக்கு, தற்போதைய அங்கீகாரம், விலையை BIS LIMS மற்றும் ஆய்வகத்தில் உறுதிசெய்க.', source:'BIS LIMS-இல் இந்தப் பதிவைப் பார்க்கவும் ↗', officialSearch:'BIS LIMS-இல் தற்போதைய IS வரம்பும் கட்டணமும் தேடுக ↗', officialLabs:'தற்போதைய BIS அங்கீகரித்த ஆய்வகங்களைத் தேடுக ↗', priceMissing:'விலை வெளியிடப்படவில்லை—ஆய்வகம்/BIS LIMS-ஐ அணுகவும்', handoff:'அதிகாரப்பூர்வ தேடலில் IS எண், ஆய்வகப் பெயர், தயாரிப்பு/தலைப்பு வடிகட்டிகள் உள்ளன. அங்கே தேடலைத் துல்லியப்படுத்தி ஒவ்வொரு முடிவின் வரம்பையும் கட்டணப் பிரிவையும் பார்க்கவும்.', hallmark:'ஹால்மார்க்கிங் மற்றும் HUID', hallmarkLead:'BIS ஹால்மார்க் என்பது விலைமதிப்புள்ள உலோகப் பொருள் BIS முறையில் குறியிடப்பட்டதைக் காட்டுகிறது. HUID என்பது பொருளில் உள்ள ஆறு எழுத்து-எண் அடையாளம்.', huidLabel:'பொருளில் உள்ள HUID', huidPlaceholder:'ஆறு எழுத்துகள் அல்லது எண்கள்', check:'உள்ளீட்டு வடிவம் சரிபார்க்கவும்', invalid:'சரியாக ஆறு எழுத்துகள் அல்லது எண்களை உள்ளிடவும். இது உள்ளீட்டு வடிவச் சரிபார்ப்பு மட்டுமே.', formatOk:'உள்ளீட்டில் ஆறு எழுத்துகள் அல்லது எண்கள் உள்ளன. BIS Bandhu இதன் உண்மைத்தன்மையைச் சரிபார்க்கவில்லை.', noVerification:'BIS Bandhu HUID, நகைக்கடைக்காரர், பொருள் அல்லது ஹால்மார்க் நிலையைச் சரிபார்க்காது.', steps:'உண்மைத்தன்மைக்கு அதிகாரப்பூர்வ BIS Care செயலியைத் திறந்து “Verify HUID” என்பதைத் தேர்ந்து, பொருளில் உள்ள குறியீட்டை உள்ளிட்டு செயலியில் முடிவைப் பார்க்கவும்.', bisCare:'அதிகாரப்பூர்வ BIS Care செயலி விவரம் ↗', hallmarkSource:'அதிகாரப்பூர்வ BIS ஹால்மார்க்கிங் தகவல் ↗' },
  bn: { labs:'পরীক্ষাগার', labsLead:'প্রাথমিক তথ্য খুঁজুন; যোগাযোগের আগে BIS LIMS-এ বর্তমান স্বীকৃতি, সঠিক পরীক্ষার পরিধি ও মূল্য নিশ্চিত করুন।', labSearch:'IS নম্বর, পণ্য, পরীক্ষাগার বা স্থান', labPlaceholder:'যেমন IS 4151, বৈদ্যুতিক খেলনা, নয়ডা…', search:'যাচাই করা রেকর্ড খুঁজুন', snapshot:'স্থানীয় BIS LIMS স্ন্যাপশট · ৩০ সেপ্টেম্বর ২০২৬ · ২টি রেকর্ড; সরাসরি বা সম্পূর্ণ তালিকা নয়', matches:'স্থানীয় যাচাই করা ফল', noMatch:'স্থানীয় রেকর্ড মেলেনি। এর অর্থ BIS LIMS-এ উপযুক্ত পরীক্ষাগার নেই, তা নয়।', scope:'তালিকাভুক্ত গ্রেড / ধরন', validity:'LIMS-এ দেখানো স্বীকৃতির মেয়াদ', fee:'তালিকাভুক্ত পরীক্ষার মূল্য (কর ছাড়া)', feeCaution:'মূল্য ও পরীক্ষার পরিধি বদলাতে পারে। সঠিক সংস্করণ, সুবিধা, ব্যতিক্রম, বর্তমান স্বীকৃতি ও মূল্য BIS LIMS এবং পরীক্ষাগারে নিশ্চিত করুন।', source:'BIS LIMS-এ রেকর্ড দেখুন ↗', officialSearch:'BIS LIMS-এ বর্তমান IS পরিধি ও মূল্য খুঁজুন ↗', officialLabs:'বর্তমান BIS স্বীকৃত পরীক্ষাগার খুঁজুন ↗', priceMissing:'মূল্য প্রকাশিত নয়—পরীক্ষাগার/BIS LIMS-এ জিজ্ঞাসা করুন', handoff:'সরকারি অনুসন্ধানে IS নম্বর, পরীক্ষাগারের নাম ও পণ্য/শিরোনাম ফিল্টার আছে। সেখানে খোঁজ সীমিত করে প্রতিটি ফলের পরিধি ও মূল্যের বিবরণ দেখুন।', hallmark:'হলমার্কিং ও HUID', hallmarkLead:'BIS হলমার্ক বোঝায় মূল্যবান ধাতুর সামগ্রী BIS ব্যবস্থায় চিহ্নিত হয়েছে। HUID হলো সামগ্রীতে থাকা ছয় অক্ষর-সংখ্যার পরিচয়।', huidLabel:'সামগ্রীতে থাকা HUID', huidPlaceholder:'ছয় অক্ষর বা সংখ্যা', check:'ইনপুটের ধরন পরীক্ষা', invalid:'ঠিক ছয়টি অক্ষর বা সংখ্যা লিখুন। এটি শুধু ইনপুটের ধরন পরীক্ষা করে।', formatOk:'ইনপুটে ছয়টি অক্ষর বা সংখ্যা আছে। BIS Bandhu এর সত্যতা যাচাই করেনি।', noVerification:'BIS Bandhu HUID, বিক্রেতা, সামগ্রী বা হলমার্কের অবস্থা যাচাই করে না।', steps:'সত্যতা যাচাই করতে সরকারি BIS Care অ্যাপ খুলুন, “Verify HUID” বাছুন, সামগ্রীতে থাকা কোড লিখুন এবং অ্যাপের ফল দেখুন।', bisCare:'সরকারি BIS Care অ্যাপের তথ্য খুলুন ↗', hallmarkSource:'সরকারি BIS হলমার্কিং তথ্য পড়ুন ↗' },
} as const;

function OfficialLink({ href, children }: { href: string; children: React.ReactNode }) {
  return <a className="official-service-link" href={href} target="_blank" rel="noopener noreferrer">{children}</a>;
}

const directoryCopy = {
  en: { snapshot:'Dated BIS LIMS snapshot', labs:'laboratories', capabilities:'sampled IS scopes', matching:'matching laboratories', loading:'Searching the local BIS LIMS snapshot…', error:'The laboratory directory could not be loaded. Try again or search BIS LIMS directly.', retry:'Retry', directoryValidity:'LIMS directory validity date', scopeValidity:'LIMS search validity date', unknown:'Not shown in snapshot', noScope:'No IS scope for this lab was captured in the sampled searches. Inspect the official scope.', noLocation:'Location not shown', labSource:'Open official lab scope ↗', amount:'Listed scope-row amount, excluding taxes', chargeNote:'Charge conditions', remarks:'Scope remarks', previous:'Previous page', next:'Next page', page:'Page', of:'of' },
  hi: { snapshot:'दिनांकित BIS LIMS स्नैपशॉट', labs:'प्रयोगशालाएँ', capabilities:'नमूना IS दायरे', matching:'मेल खाने वाली प्रयोगशालाएँ', loading:'स्थानीय BIS LIMS स्नैपशॉट खोजा जा रहा है…', error:'प्रयोगशाला निर्देशिका लोड नहीं हुई। फिर कोशिश करें या BIS LIMS में सीधे खोजें।', retry:'फिर कोशिश करें', directoryValidity:'LIMS निर्देशिका की वैधता तिथि', scopeValidity:'LIMS खोज की वैधता तिथि', unknown:'स्नैपशॉट में नहीं दिखाया गया', noScope:'नमूना खोज में इस प्रयोगशाला का IS दायरा दर्ज नहीं हुआ। आधिकारिक दायरा देखें।', noLocation:'स्थान नहीं दिखाया गया', labSource:'आधिकारिक प्रयोगशाला दायरा खोलें ↗', amount:'सूचीबद्ध दायरा-पंक्ति राशि, कर अलग', chargeNote:'शुल्क की शर्तें', remarks:'दायरे की टिप्पणियाँ', previous:'पिछला पृष्ठ', next:'अगला पृष्ठ', page:'पृष्ठ', of:'में से' },
  mr: { snapshot:'दिनांकित BIS LIMS स्नॅपशॉट', labs:'प्रयोगशाळा', capabilities:'नमुना IS व्याप्ती', matching:'जुळणाऱ्या प्रयोगशाळा', loading:'स्थानिक BIS LIMS स्नॅपशॉट शोधत आहे…', error:'प्रयोगशाळा यादी लोड झाली नाही. पुन्हा प्रयत्न करा किंवा BIS LIMS मध्ये थेट शोधा.', retry:'पुन्हा प्रयत्न करा', directoryValidity:'LIMS यादीची वैधता तारीख', scopeValidity:'LIMS शोधाची वैधता तारीख', unknown:'स्नॅपशॉटमध्ये दिसत नाही', noScope:'नमुना शोधांमध्ये या प्रयोगशाळेची IS व्याप्ती नोंदली नाही. अधिकृत व्याप्ती तपासा.', noLocation:'ठिकाण दाखवलेले नाही', labSource:'अधिकृत प्रयोगशाळा व्याप्ती उघडा ↗', amount:'नोंदवलेली व्याप्ती-पंक्ती रक्कम, कर वगळून', chargeNote:'शुल्क अटी', remarks:'व्याप्ती टिपा', previous:'मागील पान', next:'पुढील पान', page:'पान', of:'पैकी' },
  ta: { snapshot:'தேதியிட்ட BIS LIMS பதிவு', labs:'ஆய்வகங்கள்', capabilities:'மாதிரி IS சோதனை வரம்புகள்', matching:'பொருந்தும் ஆய்வகங்கள்', loading:'உள்ளூர் BIS LIMS பதிவில் தேடுகிறது…', error:'ஆய்வகப் பட்டியலை ஏற்ற முடியவில்லை. மீண்டும் முயற்சிக்கவும் அல்லது BIS LIMS-இல் தேடவும்.', retry:'மீண்டும் முயற்சிக்கவும்', directoryValidity:'LIMS பட்டியல் செல்லுபடித் தேதி', scopeValidity:'LIMS தேடல் செல்லுபடித் தேதி', unknown:'பதிவில் காட்டப்படவில்லை', noScope:'மாதிரித் தேடல்களில் இந்த ஆய்வகத்தின் IS வரம்பு பதிவாகவில்லை. அதிகாரப்பூர்வ வரம்பைப் பார்க்கவும்.', noLocation:'இடம் காட்டப்படவில்லை', labSource:'அதிகாரப்பூர்வ ஆய்வக வரம்பைத் திறக்கவும் ↗', amount:'பட்டியலிட்ட வரம்பு-வரி தொகை, வரி தவிர', chargeNote:'கட்டண நிபந்தனைகள்', remarks:'வரம்புக் குறிப்புகள்', previous:'முந்தைய பக்கம்', next:'அடுத்த பக்கம்', page:'பக்கம்', of:'இல்' },
  bn: { snapshot:'তারিখযুক্ত BIS LIMS স্ন্যাপশট', labs:'পরীক্ষাগার', capabilities:'নমুনা IS পরীক্ষার পরিধি', matching:'মিলে যাওয়া পরীক্ষাগার', loading:'স্থানীয় BIS LIMS স্ন্যাপশটে খোঁজা হচ্ছে…', error:'পরীক্ষাগারের তালিকা লোড হয়নি। আবার চেষ্টা করুন বা BIS LIMS-এ সরাসরি খুঁজুন।', retry:'আবার চেষ্টা করুন', directoryValidity:'LIMS তালিকার বৈধতার তারিখ', scopeValidity:'LIMS অনুসন্ধানের বৈধতার তারিখ', unknown:'স্ন্যাপশটে দেখানো নেই', noScope:'নমুনা অনুসন্ধানে এই পরীক্ষাগারের IS পরিধি ধরা পড়েনি। সরকারি পরিধি দেখুন।', noLocation:'স্থান দেখানো নেই', labSource:'সরকারি পরীক্ষাগার পরিধি খুলুন ↗', amount:'তালিকাভুক্ত পরিধি-সারির মূল্য, কর ছাড়া', chargeNote:'মূল্যের শর্ত', remarks:'পরিধির মন্তব্য', previous:'আগের পৃষ্ঠা', next:'পরের পৃষ্ঠা', page:'পৃষ্ঠা', of:'এর মধ্যে' },
} as const;

export function TestingLabsPage() {
  const { language } = useLanguage(); const t = copy[language]; const labels = directoryCopy[language];
  const [draft, setDraft] = useState(''); const [searched, setSearched] = useState('');
  const [response, setResponse] = useState<LaboratorySearchResponse | null>(null);
  const [loading, setLoading] = useState(false); const [error, setError] = useState(false);
  const [page, setPage] = useState(1);
  const request = useRef<AbortController | null>(null);
  const runSearch = async (value: string, nextPage: number) => {
    request.current?.abort();
    const controller = new AbortController(); request.current = controller;
    setLoading(true); setError(false);
    try {
      const result = await searchLaboratories(value, nextPage, controller.signal);
      if (!Array.isArray(result.results)) throw new Error('Malformed laboratory response');
      if (!controller.signal.aborted) { setResponse(result); setSearched(value); setPage(nextPage); }
    } catch { if (!controller.signal.aborted) setError(true); }
    finally { if (!controller.signal.aborted) setLoading(false); }
  };
  useEffect(() => { void runSearch('', 1); return () => request.current?.abort(); }, []);
  const isNumber = searched.match(/\b(?:IS\s*)?(\d{3,6})\b/i)?.[1];
  const officialSearch = isNumber ? `${LIMS_SEARCH}?is_number__doc_no=${encodeURIComponent(isNumber)}` : LIMS_SEARCH;
  const search = (event: FormEvent) => { event.preventDefault(); void runSearch(draft.trim(), 1); };
  const matches: LaboratoryResult[] = response?.results ?? [];
  const pageCount = Math.max(1, Math.ceil((response?.total_matches ?? 0) / (response?.page_size ?? 20)));
  return <section className="reference-page lab-page">
    <header className="reference-intro"><p className="eyebrow">BIS LIMS</p><h1>{t.labs}</h1><p>{t.labsLead}</p></header>
    <div className="lab-content">
      <form className="reference-search" onSubmit={search}><label htmlFor="lab-search">{t.labSearch}</label><div><input id="lab-search" value={draft} onChange={event => setDraft(event.target.value)} placeholder={t.labPlaceholder} maxLength={120}/><button>{t.search}</button></div></form>
      {loading && <p className="catalogue-meta" role="status">{labels.loading}</p>}
      {error && <div className="reference-limit" role="alert"><p>{labels.error}</p><button type="button" onClick={()=>void runSearch(searched,page)}>{labels.retry}</button></div>}
      {response && <><p className="evidence-limited">{labels.snapshot} · {response.laboratory_count} {labels.labs} · {response.capability_count} {labels.capabilities} · {response.last_updated?.slice(0,10) ?? labels.unknown}</p>
      <p className="catalogue-meta" role="status">{response.total_matches} {labels.matching}</p>
      {matches.length ? <div className="lab-results">{matches.map(({laboratory: lab,capabilities}) => <article className="reference-card" key={lab.id}>
        <div className="lab-identity"><p className="eyebrow">{lab.code || 'BIS LIMS'}</p><h2>{lab.name}</h2><p>{lab.location || labels.noLocation}</p></div>
        <div className="lab-metadata"><dl className="lab-facts"><div><dt>{labels.directoryValidity}</dt><dd>{lab.directory_valid_until || labels.unknown}</dd></div></dl>
          {capabilities.length ? capabilities.map(scope=><section className="lab-scope" key={scope.id}><h3>{scope.standard_identifier}</h3>{scope.product_title&&<p>{scope.product_title}</p>}<dl className="lab-facts">{scope.grade_type&&<div><dt>{t.scope}</dt><dd>{scope.grade_type}</dd></div>}<div><dt>{labels.scopeValidity}</dt><dd>{scope.search_validity_date || labels.unknown}</dd></div><div><dt>{labels.amount}</dt><dd>{scope.charge_amount !== null ? `₹${Number(scope.charge_amount.replaceAll(',', '')).toLocaleString('en-IN')}` : t.priceMissing}</dd></div></dl>{scope.charge_note&&<details><summary>{labels.chargeNote}</summary><p>{scope.charge_note}</p></details>}{scope.remarks&&<details><summary>{labels.remarks}</summary><p>{scope.remarks}</p></details>}<OfficialLink href={scope.source_url}>{t.source}</OfficialLink></section>) : <p>{labels.noScope}</p>}
        </div>
        <OfficialLink href={lab.official_url}>{labels.labSource}</OfficialLink>
      </article>)}</div> : !loading && <div className="reference-limit"><p>{t.noMatch}</p></div>}
      {response.total_matches > response.page_size && <nav className="directory-pagination" aria-label={labels.page}><button type="button" disabled={loading||page<=1} onClick={()=>void runSearch(searched,page-1)}>{labels.previous}</button><span>{labels.page} {page} {labels.of} {pageCount}</span><button type="button" disabled={loading||page>=pageCount} onClick={()=>void runSearch(searched,page+1)}>{labels.next}</button></nav>}</>}
      <div className="lab-followup"><p className="reference-copy">{t.feeCaution}</p><p className="reference-copy">{t.handoff}</p>
        <div className="reference-actions"><OfficialLink href={officialSearch}>{t.officialSearch}</OfficialLink><OfficialLink href={LIMS_LABS}>{t.officialLabs}</OfficialLink></div>
      </div>
    </div>
  </section>;
}

const hallmarkEntryCopy = {
  en: { heading: 'Hallmarking guidance', intro: 'Ask about jewellery marks, HUID, buying checks or the jeweller process. Answers use reviewed BIS sources.', question: 'Your hallmarking question', audience: 'I am a', placeholder: 'Ask what you need to know about BIS hallmarking…', consumer: 'Consumer', jeweller: 'Jeweller', examples: 'Try a question', ask: 'Ask Bandhu', services: 'Official BIS services', care: 'Verify HUID in BIS Care ↗', registration: 'Jeweller registration ↗', centres: 'Assaying and Hallmarking Centres ↗', complaints: 'Consumer complaints ↗', format: 'Optional HUID format check', samples: ['What should I check before buying hallmarked gold jewellery?', 'What is HUID, and how can I verify it?', 'How can a jeweller get started with BIS hallmarking?'] },
  hi: { heading: 'हॉलमार्किंग मार्गदर्शन', intro: 'आभूषण के चिह्न, HUID, खरीदते समय जाँच या जौहरी की प्रक्रिया के बारे में पूछें। उत्तर समीक्षित BIS स्रोतों पर आधारित हैं।', question: 'आपका हॉलमार्किंग प्रश्न', audience: 'मैं हूँ', placeholder: 'BIS हॉलमार्किंग के बारे में अपना प्रश्न लिखें…', consumer: 'ग्राहक', jeweller: 'जौहरी', examples: 'एक प्रश्न आज़माएँ', ask: 'Bandhu से पूछें', services: 'आधिकारिक BIS सेवाएँ', care: 'BIS Care में HUID जाँचें ↗', registration: 'जौहरी पंजीकरण ↗', centres: 'परख और हॉलमार्किंग केंद्र ↗', complaints: 'उपभोक्ता शिकायतें ↗', format: 'वैकल्पिक HUID प्रारूप जाँच', samples: ['हॉलमार्क वाले सोने के आभूषण खरीदने से पहले क्या जाँचूँ?', 'HUID क्या है और इसे कैसे जाँच सकता हूँ?', 'जौहरी BIS हॉलमार्किंग कैसे शुरू कर सकता है?'] },
  mr: { heading: 'हॉलमार्किंग मार्गदर्शन', intro: 'दागिन्यांवरील चिन्हे, HUID, खरेदीची तपासणी किंवा सराफाची प्रक्रिया याबद्दल विचारा. उत्तरे तपासलेल्या BIS स्रोतांवर आधारित आहेत.', question: 'तुमचा हॉलमार्किंग प्रश्न', audience: 'मी आहे', placeholder: 'BIS हॉलमार्किंगबद्दल प्रश्न लिहा…', consumer: 'ग्राहक', jeweller: 'सराफ', examples: 'प्रश्न वापरून पहा', ask: 'Bandhu ला विचारा', services: 'अधिकृत BIS सेवा', care: 'BIS Care मध्ये HUID तपासा ↗', registration: 'सराफ नोंदणी ↗', centres: 'परख व हॉलमार्किंग केंद्रे ↗', complaints: 'ग्राहक तक्रारी ↗', format: 'पर्यायी HUID नमुना तपासणी', samples: ['हॉलमार्क असलेले सोन्याचे दागिने खरेदीपूर्वी काय तपासावे?', 'HUID म्हणजे काय आणि ते कसे तपासावे?', 'सराफ BIS हॉलमार्किंगची सुरुवात कशी करू शकतो?'] },
  ta: { heading: 'ஹால்மார்க்கிங் வழிகாட்டல்', intro: 'நகை குறிகள், HUID, வாங்கும் முன் சோதனை அல்லது நகைக்கடைக்காரர் நடைமுறை பற்றி கேளுங்கள். பதில்கள் பரிசீலித்த BIS ஆதாரங்களைப் பயன்படுத்துகின்றன.', question: 'உங்கள் ஹால்மார்க்கிங் கேள்வி', audience: 'நான்', placeholder: 'BIS ஹால்மார்க்கிங் பற்றி கேளுங்கள்…', consumer: 'நுகர்வோர்', jeweller: 'நகைக்கடைக்காரர்', examples: 'ஒரு கேள்வியை முயற்சிக்கவும்', ask: 'Bandhu-விடம் கேளுங்கள்', services: 'அதிகாரப்பூர்வ BIS சேவைகள்', care: 'BIS Care-இல் HUID சரிபார்க்கவும் ↗', registration: 'நகைக்கடைக்காரர் பதிவு ↗', centres: 'சோதனை மற்றும் ஹால்மார்க்கிங் மையங்கள் ↗', complaints: 'நுகர்வோர் புகார்கள் ↗', format: 'விருப்ப HUID வடிவச் சரிபார்ப்பு', samples: ['ஹால்மார்க் தங்க நகை வாங்குவதற்கு முன் என்ன பார்க்க வேண்டும்?', 'HUID என்றால் என்ன, அதை எப்படிச் சரிபார்ப்பது?', 'நகைக்கடைக்காரர் BIS ஹால்மார்க்கிங்கை எப்படித் தொடங்கலாம்?'] },
  bn: { heading: 'হলমার্কিং নির্দেশনা', intro: 'গয়নার চিহ্ন, HUID, কেনার আগে পরীক্ষা বা জুয়েলারির প্রক্রিয়া নিয়ে প্রশ্ন করুন। উত্তর পর্যালোচিত BIS উৎসভিত্তিক।', question: 'আপনার হলমার্কিং প্রশ্ন', audience: 'আমি', placeholder: 'BIS হলমার্কিং নিয়ে প্রশ্ন লিখুন…', consumer: 'ভোক্তা', jeweller: 'জুয়েলারি বিক্রেতা', examples: 'একটি প্রশ্ন চেষ্টা করুন', ask: 'Bandhu-কে জিজ্ঞাসা করুন', services: 'সরকারি BIS পরিষেবা', care: 'BIS Care-এ HUID যাচাই করুন ↗', registration: 'জুয়েলারি বিক্রেতার নিবন্ধন ↗', centres: 'অ্যাসেয়িং ও হলমার্কিং কেন্দ্র ↗', complaints: 'ভোক্তার অভিযোগ ↗', format: 'ঐচ্ছিক HUID বিন্যাস পরীক্ষা', samples: ['হলমার্কযুক্ত সোনার গয়না কেনার আগে কী পরীক্ষা করব?', 'HUID কী এবং কীভাবে তা যাচাই করব?', 'জুয়েলারি বিক্রেতা কীভাবে BIS হলমার্কিং শুরু করবেন?'] },
} as const;

export function HallmarkingPage({ onAsk }: { onAsk?: (question: string, audience: Audience) => void }) {
  const { language } = useLanguage();
  const t = copy[language];
  const entry = hallmarkEntryCopy[language];
  const [draft, setDraft] = useState('');
  const [audience, setAudience] = useState<Audience>('consumer');
  const [huid, setHuid] = useState('');
  const [checked, setChecked] = useState(false);
  const questionInput = useRef<HTMLTextAreaElement>(null);
  const formatOk = /^[A-Za-z0-9]{6}$/.test(huid.trim());
  const submit = (event: FormEvent) => {
    event.preventDefault();
    if (draft.trim()) onAsk?.(draft.trim(), audience);
  };
  return <section className="reference-page hallmark-page">
    <header className="reference-intro"><p className="eyebrow">BIS Bandhu</p><h1>{entry.heading}</h1><p>{entry.intro}</p></header>
    <form className="hallmark-ask" onSubmit={submit}>
      <div className="hallmark-audience" role="group" aria-label={entry.audience}>
        <label><input type="radio" name="hallmark-audience" checked={audience === 'consumer'} onChange={() => setAudience('consumer')} />{entry.consumer}</label>
        <label><input type="radio" name="hallmark-audience" checked={audience === 'manufacturer'} onChange={() => setAudience('manufacturer')} />{entry.jeweller}</label>
      </div>
      <label htmlFor="hallmark-question">{entry.question}</label>
      <textarea ref={questionInput} id="hallmark-question" value={draft} onChange={event => setDraft(event.target.value)} maxLength={1000} placeholder={entry.placeholder} />
      <div className="hallmark-compose-actions"><SpeechInput value={draft} onTranscript={setDraft} /><button type="submit" disabled={!draft.trim()}>{entry.ask}</button></div>
    </form>
    <div className="hallmark-examples"><p>{entry.examples}</p><div>{entry.samples.map((sample, index) => <button type="button" key={sample} onClick={() => { setDraft(sample); setAudience(index === 2 ? 'manufacturer' : 'consumer'); questionInput.current?.focus(); }}>{sample}</button>)}</div></div>
    <section className="hallmark-services" aria-label={entry.services}><h2>{entry.services}</h2><div className="reference-actions"><OfficialLink href={BIS_CARE}>{entry.care}</OfficialLink><OfficialLink href={BIS_JEWELLERS}>{entry.registration}</OfficialLink><OfficialLink href={BIS_CENTRES}>{entry.centres}</OfficialLink><OfficialLink href={BIS_COMPLAINTS}>{entry.complaints}</OfficialLink></div></section>
    <details className="hallmark-format"><summary>{entry.format}</summary><p>{t.noVerification}</p><form className="reference-search" onSubmit={event => { event.preventDefault(); setChecked(true); }}><label htmlFor="huid-input">{t.huidLabel}</label><div><input id="huid-input" value={huid} onChange={event => { setHuid(event.target.value.toUpperCase()); setChecked(false); }} placeholder={t.huidPlaceholder} autoComplete="off" spellCheck={false}/><button>{t.check}</button></div></form>{checked && <p className="huid-format" role="status">{formatOk ? t.formatOk : t.invalid}</p>}</details>
  </section>;
}
