import { useState, type FormEvent } from 'react';
import { useLanguage } from '../i18n/LanguageContext';

const LIMS_SEARCH = 'https://lims.bis.gov.in/home/search_is_number/';
const LIMS_LABS = 'https://lims.bis.gov.in/home/labs/';
const BIS_CARE = 'https://www.bis.gov.in/bis-apps/?lang=en';
const BIS_HALLMARKING = 'https://www.bis.gov.in/hallmarking-overview/?lang=en';

/** Small, dated observations from BIS LIMS; this is not a live or complete laboratory feed. */
export const checkedLabs = [
  {
    name: 'PRESTO LABORATORIES PRIVATE LIMITED', location: 'Faridabad, Haryana', code: '8199006',
    standard: 'IS 4151:2015', product: 'Protective helmets for motorcycle riders',
    scope: 'All', validUntil: '21 Aug 2029', charge: '₹14,000',
    source: 'https://lims.bis.gov.in/home/search_is_number/?is_number__doc_no=4151',
  },
  {
    name: 'Testtex India Laboratories Private Limited, Noida', location: 'Noida, Uttar Pradesh', code: '8138306',
    standard: 'IS 15644:2006', product: 'Safety of electric toys',
    scope: 'All', validUntil: '31 Dec 2029', charge: '₹13,500',
    source: 'https://lims.bis.gov.in/home/search_is_number/?is_number__doc_no=15644',
  },
] as const;

const copy = {
  en: { labs:'Testing laboratories', labsLead:'Find a starting point, then confirm the current recognition, exact test scope and price in BIS LIMS before contacting a lab.', labSearch:'IS number, product, laboratory or location', labPlaceholder:'Try IS 4151, electric toys, Noida…', search:'Search checked records', snapshot:'Locally checked BIS LIMS snapshot · 30 Sep 2026 · 2 records, not a live or complete BIS directory', matches:'checked local matches', noMatch:'No checked local record matches. This does not mean BIS LIMS has no suitable lab.', scope:'Listed grade / type', validity:'Recognition validity shown by LIMS', fee:'Listed testing charge (excluding taxes)', feeCaution:'Charges and test coverage may vary. Confirm the exact edition, test facilities, exclusions, current recognition and quotation with BIS LIMS and the lab.', source:'Check this record in BIS LIMS ↗', officialSearch:'Search current IS scope and testing charges in BIS LIMS ↗', officialLabs:'Search the current BIS recognised-labs list ↗', priceMissing:'Price not published—check with lab/BIS LIMS', handoff:'The official search supports IS number, lab name and product/title filters. Refine the search there and inspect each result’s scope and charge breakup.', hallmark:'Hallmarking and HUID', hallmarkLead:'A BIS hallmark indicates that a precious-metal article has been marked under the BIS hallmarking system. The HUID is a six-character alphanumeric identifier on a hallmarked article.', huidLabel:'HUID printed on the article', huidPlaceholder:'Six letters or digits', check:'Check input format', invalid:'Enter exactly six letters or digits. This is only an input-format check.', formatOk:'The input has six letters or digits. Its authenticity has NOT been verified by BIS Bandhu.', noVerification:'BIS Bandhu does not verify HUID authenticity, jewellers, articles or hallmark status.', steps:'To check authenticity: open the official BIS Care app, choose “Verify HUID”, enter the code as printed on the article, and review the result in the app.', bisCare:'Open official BIS Care app information ↗', hallmarkSource:'Read official BIS hallmarking information ↗' },
  hi: { labs:'परीक्षण प्रयोगशालाएँ', labsLead:'प्रारंभिक जानकारी देखें, फिर प्रयोगशाला से संपर्क करने से पहले BIS LIMS में वर्तमान मान्यता, सटीक परीक्षण दायरा और मूल्य की पुष्टि करें।', labSearch:'IS नंबर, उत्पाद, प्रयोगशाला या स्थान', labPlaceholder:'जैसे IS 4151, बिजली के खिलौने, नोएडा…', search:'जाँचे गए रिकॉर्ड खोजें', snapshot:'स्थानीय BIS LIMS स्नैपशॉट · 30 सितम्बर 2026 · 2 रिकॉर्ड; पूर्ण या लाइव निर्देशिका नहीं', matches:'स्थानीय जाँचे गए परिणाम', noMatch:'कोई जाँचा गया स्थानीय रिकॉर्ड नहीं मिला। इसका अर्थ यह नहीं कि BIS LIMS में उपयुक्त प्रयोगशाला नहीं है।', scope:'सूचीबद्ध ग्रेड / प्रकार', validity:'LIMS में दिखाई गई मान्यता अवधि', fee:'सूचीबद्ध परीक्षण शुल्क (कर अलग)', feeCaution:'शुल्क और परीक्षण कवरेज बदल सकते हैं। BIS LIMS और प्रयोगशाला से संस्करण, परीक्षण सुविधाएँ, अपवाद, वर्तमान मान्यता और कीमत जाँचें।', source:'BIS LIMS में यह रिकॉर्ड देखें ↗', officialSearch:'BIS LIMS में वर्तमान IS दायरा और शुल्क खोजें ↗', officialLabs:'वर्तमान BIS मान्यता प्राप्त प्रयोगशालाएँ खोजें ↗', priceMissing:'कीमत प्रकाशित नहीं—प्रयोगशाला/BIS LIMS से पूछें', handoff:'आधिकारिक खोज IS नंबर, प्रयोगशाला नाम और उत्पाद/शीर्षक फ़िल्टर देती है। वहाँ खोज सुधारें और हर परिणाम का दायरा व शुल्क विवरण देखें।', hallmark:'हॉलमार्किंग और HUID', hallmarkLead:'BIS हॉलमार्क दर्शाता है कि बहुमूल्य धातु की वस्तु BIS हॉलमार्किंग प्रणाली में चिह्नित है। HUID हॉलमार्क वाली वस्तु पर छह अक्षरों या अंकों का पहचानकर्ता है।', huidLabel:'वस्तु पर लिखा HUID', huidPlaceholder:'छह अक्षर या अंक', check:'इनपुट प्रारूप जाँचें', invalid:'ठीक छह अक्षर या अंक लिखें। यह केवल इनपुट प्रारूप की जाँच है।', formatOk:'इनपुट में छह अक्षर या अंक हैं। BIS Bandhu ने इसकी प्रामाणिकता सत्यापित नहीं की है।', noVerification:'BIS Bandhu HUID, जौहरी, वस्तु या हॉलमार्क स्थिति सत्यापित नहीं करता।', steps:'प्रामाणिकता जाँचने के लिए आधिकारिक BIS Care ऐप खोलें, “Verify HUID” चुनें, वस्तु पर लिखा कोड दर्ज करें और ऐप में परिणाम देखें।', bisCare:'आधिकारिक BIS Care ऐप जानकारी खोलें ↗', hallmarkSource:'आधिकारिक BIS हॉलमार्किंग जानकारी पढ़ें ↗' },
  mr: { labs:'चाचणी प्रयोगशाळा', labsLead:'प्रारंभिक माहिती शोधा; प्रयोगशाळेशी संपर्क करण्यापूर्वी BIS LIMS मध्ये सध्याची मान्यता, नेमकी चाचणी व्याप्ती आणि किंमत तपासा.', labSearch:'IS क्रमांक, उत्पादन, प्रयोगशाळा किंवा ठिकाण', labPlaceholder:'उदा. IS 4151, विद्युत खेळणी, नोएडा…', search:'तपासलेल्या नोंदी शोधा', snapshot:'स्थानिक BIS LIMS स्नॅपशॉट · 30 सप्टेंबर 2026 · 2 नोंदी; संपूर्ण किंवा थेट यादी नाही', matches:'स्थानिक तपासलेले परिणाम', noMatch:'जुळणारी स्थानिक नोंद नाही. याचा अर्थ BIS LIMS मध्ये योग्य प्रयोगशाळा नाही असे नाही.', scope:'नोंदवलेला दर्जा / प्रकार', validity:'LIMS वरील मान्यता मुदत', fee:'नोंदवलेले चाचणी शुल्क (कर वगळून)', feeCaution:'शुल्क आणि चाचणी व्याप्ती बदलू शकते. नेमकी आवृत्ती, सुविधा, अपवाद, सध्याची मान्यता आणि किंमत BIS LIMS व प्रयोगशाळेकडून तपासा.', source:'BIS LIMS मधील ही नोंद तपासा ↗', officialSearch:'BIS LIMS मध्ये सध्याची IS व्याप्ती व शुल्क शोधा ↗', officialLabs:'सध्याची BIS मान्यताप्राप्त प्रयोगशाळा यादी शोधा ↗', priceMissing:'किंमत प्रसिद्ध नाही—प्रयोगशाळा/BIS LIMS कडे चौकशी करा', handoff:'अधिकृत शोधात IS क्रमांक, प्रयोगशाळा नाव आणि उत्पादन/शीर्षक फिल्टर आहेत. तिथे शोध सुधारून प्रत्येक निकालाची व्याप्ती व शुल्क तपासा.', hallmark:'हॉलमार्किंग आणि HUID', hallmarkLead:'BIS हॉलमार्क म्हणजे मौल्यवान धातूची वस्तू BIS हॉलमार्किंग व्यवस्थेनुसार चिन्हांकित आहे. HUID हा वस्तूवरील सहा अक्षरी-अंकी ओळख क्रमांक आहे.', huidLabel:'वस्तूवरील HUID', huidPlaceholder:'सहा अक्षरे किंवा अंक', check:'इनपुटचा नमुना तपासा', invalid:'नेमकी सहा अक्षरे किंवा अंक लिहा. ही फक्त इनपुटच्या नमुन्याची तपासणी आहे.', formatOk:'इनपुटमध्ये सहा अक्षरे किंवा अंक आहेत. BIS Bandhu ने त्याची अस्सलता तपासलेली नाही.', noVerification:'BIS Bandhu HUID, विक्रेता, वस्तू किंवा हॉलमार्क स्थिती सत्यापित करत नाही.', steps:'अस्सलता तपासण्यासाठी अधिकृत BIS Care अ‍ॅप उघडा, “Verify HUID” निवडा, वस्तूवरील कोड टाका आणि अ‍ॅपमधील निकाल पाहा.', bisCare:'अधिकृत BIS Care अ‍ॅपची माहिती उघडा ↗', hallmarkSource:'अधिकृत BIS हॉलमार्किंग माहिती वाचा ↗' },
  ta: { labs:'சோதனை ஆய்வகங்கள்', labsLead:'தொடக்கத் தகவலைத் தேடி, ஆய்வகத்தை அணுகுமுன் BIS LIMS-இல் தற்போதைய அங்கீகாரம், துல்லிய சோதனை வரம்பு, கட்டணத்தை உறுதிசெய்க.', labSearch:'IS எண், தயாரிப்பு, ஆய்வகம் அல்லது இடம்', labPlaceholder:'எ.கா. IS 4151, மின்சார பொம்மை, நொய்டா…', search:'சரிபார்த்த பதிவுகளைத் தேடுக', snapshot:'உள்ளூர் BIS LIMS பதிவு · 30 செப்டம்பர் 2026 · 2 பதிவுகள்; நேரடி அல்லது முழுப் பட்டியல் அல்ல', matches:'உள்ளூரில் சரிபார்த்த பொருத்தங்கள்', noMatch:'உள்ளூரில் பொருந்தும் பதிவு இல்லை. BIS LIMS-இல் பொருத்தமான ஆய்வகம் இல்லை என்று இதன் பொருள் அல்ல.', scope:'பட்டியலிடப்பட்ட தரம் / வகை', validity:'LIMS காட்டும் அங்கீகாரக் காலம்', fee:'பட்டியலிடப்பட்ட சோதனைக் கட்டணம் (வரி தவிர)', feeCaution:'கட்டணமும் சோதனை வரம்பும் மாறலாம். சரியான பதிப்பு, வசதி, விதிவிலக்கு, தற்போதைய அங்கீகாரம், விலையை BIS LIMS மற்றும் ஆய்வகத்தில் உறுதிசெய்க.', source:'BIS LIMS-இல் இந்தப் பதிவைப் பார்க்கவும் ↗', officialSearch:'BIS LIMS-இல் தற்போதைய IS வரம்பும் கட்டணமும் தேடுக ↗', officialLabs:'தற்போதைய BIS அங்கீகரித்த ஆய்வகங்களைத் தேடுக ↗', priceMissing:'விலை வெளியிடப்படவில்லை—ஆய்வகம்/BIS LIMS-ஐ அணுகவும்', handoff:'அதிகாரப்பூர்வ தேடலில் IS எண், ஆய்வகப் பெயர், தயாரிப்பு/தலைப்பு வடிகட்டிகள் உள்ளன. அங்கே தேடலைத் துல்லியப்படுத்தி ஒவ்வொரு முடிவின் வரம்பையும் கட்டணப் பிரிவையும் பார்க்கவும்.', hallmark:'ஹால்மார்க்கிங் மற்றும் HUID', hallmarkLead:'BIS ஹால்மார்க் என்பது விலைமதிப்புள்ள உலோகப் பொருள் BIS முறையில் குறியிடப்பட்டதைக் காட்டுகிறது. HUID என்பது பொருளில் உள்ள ஆறு எழுத்து-எண் அடையாளம்.', huidLabel:'பொருளில் உள்ள HUID', huidPlaceholder:'ஆறு எழுத்துகள் அல்லது எண்கள்', check:'உள்ளீட்டு வடிவம் சரிபார்க்கவும்', invalid:'சரியாக ஆறு எழுத்துகள் அல்லது எண்களை உள்ளிடவும். இது உள்ளீட்டு வடிவச் சரிபார்ப்பு மட்டுமே.', formatOk:'உள்ளீட்டில் ஆறு எழுத்துகள் அல்லது எண்கள் உள்ளன. BIS Bandhu இதன் உண்மைத்தன்மையைச் சரிபார்க்கவில்லை.', noVerification:'BIS Bandhu HUID, நகைக்கடைக்காரர், பொருள் அல்லது ஹால்மார்க் நிலையைச் சரிபார்க்காது.', steps:'உண்மைத்தன்மைக்கு அதிகாரப்பூர்வ BIS Care செயலியைத் திறந்து “Verify HUID” என்பதைத் தேர்ந்து, பொருளில் உள்ள குறியீட்டை உள்ளிட்டு செயலியில் முடிவைப் பார்க்கவும்.', bisCare:'அதிகாரப்பூர்வ BIS Care செயலி விவரம் ↗', hallmarkSource:'அதிகாரப்பூர்வ BIS ஹால்மார்க்கிங் தகவல் ↗' },
  bn: { labs:'পরীক্ষাগার', labsLead:'প্রাথমিক তথ্য খুঁজুন; যোগাযোগের আগে BIS LIMS-এ বর্তমান স্বীকৃতি, সঠিক পরীক্ষার পরিধি ও মূল্য নিশ্চিত করুন।', labSearch:'IS নম্বর, পণ্য, পরীক্ষাগার বা স্থান', labPlaceholder:'যেমন IS 4151, বৈদ্যুতিক খেলনা, নয়ডা…', search:'যাচাই করা রেকর্ড খুঁজুন', snapshot:'স্থানীয় BIS LIMS স্ন্যাপশট · ৩০ সেপ্টেম্বর ২০২৬ · ২টি রেকর্ড; সরাসরি বা সম্পূর্ণ তালিকা নয়', matches:'স্থানীয় যাচাই করা ফল', noMatch:'স্থানীয় রেকর্ড মেলেনি। এর অর্থ BIS LIMS-এ উপযুক্ত পরীক্ষাগার নেই, তা নয়।', scope:'তালিকাভুক্ত গ্রেড / ধরন', validity:'LIMS-এ দেখানো স্বীকৃতির মেয়াদ', fee:'তালিকাভুক্ত পরীক্ষার মূল্য (কর ছাড়া)', feeCaution:'মূল্য ও পরীক্ষার পরিধি বদলাতে পারে। সঠিক সংস্করণ, সুবিধা, ব্যতিক্রম, বর্তমান স্বীকৃতি ও মূল্য BIS LIMS এবং পরীক্ষাগারে নিশ্চিত করুন।', source:'BIS LIMS-এ রেকর্ড দেখুন ↗', officialSearch:'BIS LIMS-এ বর্তমান IS পরিধি ও মূল্য খুঁজুন ↗', officialLabs:'বর্তমান BIS স্বীকৃত পরীক্ষাগার খুঁজুন ↗', priceMissing:'মূল্য প্রকাশিত নয়—পরীক্ষাগার/BIS LIMS-এ জিজ্ঞাসা করুন', handoff:'সরকারি অনুসন্ধানে IS নম্বর, পরীক্ষাগারের নাম ও পণ্য/শিরোনাম ফিল্টার আছে। সেখানে খোঁজ সীমিত করে প্রতিটি ফলের পরিধি ও মূল্যের বিবরণ দেখুন।', hallmark:'হলমার্কিং ও HUID', hallmarkLead:'BIS হলমার্ক বোঝায় মূল্যবান ধাতুর সামগ্রী BIS ব্যবস্থায় চিহ্নিত হয়েছে। HUID হলো সামগ্রীতে থাকা ছয় অক্ষর-সংখ্যার পরিচয়।', huidLabel:'সামগ্রীতে থাকা HUID', huidPlaceholder:'ছয় অক্ষর বা সংখ্যা', check:'ইনপুটের ধরন পরীক্ষা', invalid:'ঠিক ছয়টি অক্ষর বা সংখ্যা লিখুন। এটি শুধু ইনপুটের ধরন পরীক্ষা করে।', formatOk:'ইনপুটে ছয়টি অক্ষর বা সংখ্যা আছে। BIS Bandhu এর সত্যতা যাচাই করেনি।', noVerification:'BIS Bandhu HUID, বিক্রেতা, সামগ্রী বা হলমার্কের অবস্থা যাচাই করে না।', steps:'সত্যতা যাচাই করতে সরকারি BIS Care অ্যাপ খুলুন, “Verify HUID” বাছুন, সামগ্রীতে থাকা কোড লিখুন এবং অ্যাপের ফল দেখুন।', bisCare:'সরকারি BIS Care অ্যাপের তথ্য খুলুন ↗', hallmarkSource:'সরকারি BIS হলমার্কিং তথ্য পড়ুন ↗' },
} as const;

function OfficialLink({ href, children }: { href: string; children: React.ReactNode }) {
  return <a className="official-service-link" href={href} target="_blank" rel="noopener noreferrer">{children}</a>;
}

export function TestingLabsPage() {
  const { language } = useLanguage(); const t = copy[language];
  const [draft, setDraft] = useState(''); const [searched, setSearched] = useState('');
  const needle = searched.trim().toLocaleLowerCase();
  const matches = checkedLabs.filter(lab => !needle || [lab.name, lab.location, lab.code, lab.standard, lab.product].some(field => field.toLocaleLowerCase().includes(needle)));
  const isNumber = searched.match(/\b(?:IS\s*)?(\d{3,6})\b/i)?.[1];
  const officialSearch = isNumber ? `${LIMS_SEARCH}?is_number__doc_no=${encodeURIComponent(isNumber)}` : LIMS_SEARCH;
  const search = (event: FormEvent) => { event.preventDefault(); setSearched(draft.trim()); };
  return <section className="reference-page lab-page">
    <header className="reference-intro"><p className="eyebrow">BIS LIMS</p><h1>{t.labs}</h1><p>{t.labsLead}</p></header>
    <form className="reference-search" onSubmit={search}><label htmlFor="lab-search">{t.labSearch}</label><div><input id="lab-search" value={draft} onChange={event => setDraft(event.target.value)} placeholder={t.labPlaceholder} maxLength={120}/><button>{t.search}</button></div></form>
    <p className="evidence-limited">{t.snapshot}</p>
    <p className="catalogue-meta" role="status">{matches.length} {t.matches}</p>
    {matches.length ? <div className="lab-results">{matches.map(lab => <article className="reference-card" key={lab.code}>
      <p className="eyebrow">{lab.standard} · {lab.code}</p><h2>{lab.name}</h2><p>{lab.location} · {lab.product}</p>
      <dl className="lab-facts"><div><dt>{t.scope}</dt><dd>{lab.scope}</dd></div><div><dt>{t.validity}</dt><dd>{lab.validUntil}</dd></div><div><dt>{t.fee}</dt><dd>{lab.charge || t.priceMissing}</dd></div></dl>
      <OfficialLink href={lab.source}>{t.source}</OfficialLink>
    </article>)}</div> : <div className="reference-limit"><p>{t.noMatch}</p></div>}
    <p className="reference-copy">{t.feeCaution}</p><p className="reference-copy">{t.handoff}</p>
    <div className="reference-actions"><OfficialLink href={officialSearch}>{t.officialSearch}</OfficialLink><OfficialLink href={LIMS_LABS}>{t.officialLabs}</OfficialLink></div>
  </section>;
}

export function HallmarkingPage() {
  const { language } = useLanguage(); const t = copy[language];
  const [huid, setHuid] = useState(''); const [checked, setChecked] = useState(false);
  const formatOk = /^[A-Za-z0-9]{6}$/.test(huid.trim());
  return <section className="reference-page hallmark-page">
    <header className="reference-intro"><p className="eyebrow">BIS Care</p><h1>{t.hallmark}</h1><p>{t.hallmarkLead}</p></header>
    <div className="reference-limit"><p>{t.noVerification}</p></div>
    <form className="reference-search" onSubmit={event => { event.preventDefault(); setChecked(true); }}><label htmlFor="huid-input">{t.huidLabel}</label><div><input id="huid-input" value={huid} onChange={event => { setHuid(event.target.value.toUpperCase()); setChecked(false); }} placeholder={t.huidPlaceholder} autoComplete="off" spellCheck={false}/><button>{t.check}</button></div></form>
    {checked && <p className="huid-format" role="status">{formatOk ? t.formatOk : t.invalid}</p>}
    <p className="reference-copy">{t.steps}</p>
    <div className="reference-actions"><OfficialLink href={BIS_CARE}>{t.bisCare}</OfficialLink><OfficialLink href={BIS_HALLMARKING}>{t.hallmarkSource}</OfficialLink></div>
  </section>;
}
