import { FormEvent, useEffect, useState } from 'react';
import type { ReactNode } from 'react';
import type { Audience } from '../types/chat';
import { useLanguage } from '../i18n/LanguageContext';

export type ReferencePage =
  | 'standards' | 'standard-detail' | 'compare' | 'finder' | 'applicability'
  | 'certification-guide' | 'certification-journey' | 'checklist' | 'labs' | 'lab-detail'
  | 'consumers' | 'verify-product' | 'verify-licence' | 'verify-huid' | 'complaints'
  | 'hallmarking' | 'services' | 'help' | 'how-it-works' | 'session';

type Props = {
  page: ReferencePage;
  navigate: (page: ReferencePage) => void;
  ask: (question: string, audience?: Audience) => void;
  openWizard: () => void;
  openAudience: (audience: Audience) => void;
};

const official = {
  standards: 'https://standards.bis.gov.in/',
  care: 'https://www.bis.gov.in/bis-apps/?lang=en',
  consumer: 'https://www.bis.gov.in/consumer-overview/',
  certification: 'https://www.bis.gov.in/product-certification/product-certification-process/?lang=en',
  labs: 'https://www.bis.gov.in/laboratory-recognition-scheme/',
  complaints: 'https://www.bis.gov.in/consumer-overview/complaints/',
  hallmarking: 'https://www.bis.gov.in/hallmarking-overview/',
};

const copy = {
  en: { demo: 'Demo data — illustrative only', title: 'Choose a useful next step', lead: 'Use evidence-backed guidance where the current indexed documents support it. Other services open the relevant official BIS route.', search: 'Search standards', compare: 'Compare standards', ask: 'Ask Bandhu', details: 'View details', official: 'Open official BIS service ↗', unavailable: 'Not enough indexed evidence', unavailableLead: 'BIS Bandhu cannot make a factual determination from the current indexed documents. Ask a more specific question or use the official BIS service.', finder: 'Product → Standard Finder', applicability: 'Applicability Checker', guide: 'Certification Guide', journey: 'Certification Journey', checklist: 'Document Checklist', labs: 'Testing Laboratories', consumers: 'Consumer hub', verifyProduct: 'Verify product', verifyLicence: 'Verify licence', verifyHuid: 'Verify HUID', complaints: 'Complaints', hallmarking: 'Hallmarking information', services: 'BIS Services', help: 'Help', how: 'How it works', session: 'My session', demoResult: 'This illustrative screen has not verified a product, licence, HUID, laboratory, standard, or BIS status.', searchLabel: 'Product, keyword, or IS number', searchPlaceholder: 'Describe a product or enter an IS number', saved: 'Saved on this device', delete: 'Delete local session data', empty: 'No local searches or checklist progress yet.', checklistLead: 'Use this local preparation list. It is not an official application or submission.', coverage: 'BIS Bandhu is not a complete BIS catalogue. Current answers are limited to documents indexed for this prototype and always show their sources when evidence is available.' },
  hi: { demo: 'डेमो डेटा — केवल उदाहरण', title: 'स्पष्ट अगले कदम के साथ BIS सेवाएँ', lead: 'जहाँ वर्तमान सूचीबद्ध दस्तावेज़ समर्थन देते हैं, वहाँ साक्ष्य-आधारित मार्गदर्शन लें। अन्य सेवाएँ संबंधित आधिकारिक BIS मार्ग खोलती हैं।', search: 'मानक खोजें', compare: 'मानकों की तुलना करें', ask: 'Bandhu से पूछें', details: 'विवरण देखें', official: 'आधिकारिक BIS सेवा खोलें ↗', unavailable: 'पर्याप्त सूचीबद्ध साक्ष्य नहीं', unavailableLead: 'वर्तमान सूचीबद्ध दस्तावेज़ों से BIS Bandhu तथ्यात्मक निर्धारण नहीं कर सकता। अधिक विशिष्ट प्रश्न पूछें या आधिकारिक BIS सेवा उपयोग करें।', finder: 'उत्पाद → मानक खोजक', applicability: 'लागू होने की जाँच', guide: 'प्रमाणन मार्गदर्शिका', journey: 'प्रमाणन यात्रा', checklist: 'दस्तावेज़ सूची', labs: 'परीक्षण प्रयोगशालाएँ', consumers: 'उपभोक्ता केंद्र', verifyProduct: 'उत्पाद सत्यापित करें', verifyLicence: 'लाइसेंस सत्यापित करें', verifyHuid: 'HUID सत्यापित करें', complaints: 'शिकायतें', hallmarking: 'हॉलमार्किंग जानकारी', services: 'BIS सेवाएँ', help: 'सहायता', how: 'यह कैसे काम करता है', session: 'मेरा सत्र', demoResult: 'इस उदाहरण स्क्रीन ने किसी उत्पाद, लाइसेंस, HUID, प्रयोगशाला, मानक या BIS स्थिति को सत्यापित नहीं किया है।', searchLabel: 'उत्पाद, कीवर्ड या IS नंबर', searchPlaceholder: 'उत्पाद बताइए या IS नंबर दर्ज करें', saved: 'इस डिवाइस पर सहेजा गया', delete: 'स्थानीय सत्र डेटा हटाएँ', empty: 'अभी कोई स्थानीय खोज या सूची प्रगति नहीं है।', checklistLead: 'इस स्थानीय तैयारी सूची का उपयोग करें। यह आधिकारिक आवेदन या प्रस्तुति नहीं है।', coverage: 'BIS Bandhu पूर्ण BIS सूची नहीं है। इस प्रोटोटाइप के सूचीबद्ध दस्तावेज़ों तक उत्तर सीमित हैं और साक्ष्य मिलने पर स्रोत दिखते हैं।' },
  mr: { demo: 'डेमो डेटा — केवळ उदाहरण', title: 'स्पष्ट पुढील पायरीसह BIS सेवा', lead: 'सध्याचे अनुक्रमित दस्तऐवज समर्थन देतात तेथे पुरावा-आधारित मार्गदर्शन वापरा. इतर सेवा संबंधित अधिकृत BIS मार्ग उघडतात.', search: 'मानके शोधा', compare: 'मानकांची तुलना करा', ask: 'Bandhu ला विचारा', details: 'तपशील पहा', official: 'अधिकृत BIS सेवा उघडा ↗', unavailable: 'पुरेसा अनुक्रमित पुरावा नाही', unavailableLead: 'सध्याच्या अनुक्रमित दस्तऐवजांवरून BIS Bandhu तथ्यात्मक निर्धारण करू शकत नाही. अधिक नेमका प्रश्न विचारा किंवा अधिकृत BIS सेवा वापरा.', finder: 'उत्पादन → मानक शोधक', applicability: 'लागूपणा तपासक', guide: 'प्रमाणन मार्गदर्शक', journey: 'प्रमाणन प्रवास', checklist: 'दस्तऐवज सूची', labs: 'चाचणी प्रयोगशाळा', consumers: 'ग्राहक केंद्र', verifyProduct: 'उत्पादन तपासा', verifyLicence: 'परवाना तपासा', verifyHuid: 'HUID तपासा', complaints: 'तक्रारी', hallmarking: 'हॉलमार्किंग माहिती', services: 'BIS सेवा', help: 'मदत', how: 'हे कसे कार्य करते', session: 'माझे सत्र', demoResult: 'या उदाहरण स्क्रीनने कोणतेही उत्पादन, परवाना, HUID, प्रयोगशाळा, मानक किंवा BIS स्थिती तपासलेली नाही.', searchLabel: 'उत्पादन, कीवर्ड किंवा IS क्रमांक', searchPlaceholder: 'उत्पादनाचे वर्णन करा किंवा IS क्रमांक टाका', saved: 'या उपकरणावर जतन केले', delete: 'स्थानिक सत्र डेटा हटवा', empty: 'अजून स्थानिक शोध किंवा सूची प्रगती नाही.', checklistLead: 'ही स्थानिक तयारी सूची वापरा. हा अधिकृत अर्ज किंवा सादरीकरण नाही.', coverage: 'BIS Bandhu ही पूर्ण BIS सूची नाही. उत्तर या नमुन्यासाठी अनुक्रमित दस्तऐवजांपुरते मर्यादित आहेत आणि पुरावा असल्यास स्रोत दाखवतात.' },
  ta: { demo: 'டெமோ தரவு — விளக்கத்திற்காக மட்டும்', title: 'தெளிவான அடுத்த படியுடன் BIS சேவைகள்', lead: 'தற்போதைய குறியிடப்பட்ட ஆவணங்கள் ஆதரிக்கும் இடங்களில் ஆதார-அடிப்படையிலான வழிகாட்டலைப் பயன்படுத்தவும். பிற சேவைகள் தொடர்புடைய அதிகாரப்பூர்வ BIS வழியைத் திறக்கும்.', search: 'தரநிலைகளைத் தேடுக', compare: 'தரநிலைகளை ஒப்பிடுக', ask: 'Bandhu-விடம் கேளுங்கள்', details: 'விவரங்களைக் காண்க', official: 'அதிகாரப்பூர்வ BIS சேவையைத் திறக்கவும் ↗', unavailable: 'போதுமான குறியிடப்பட்ட ஆதாரம் இல்லை', unavailableLead: 'தற்போதைய குறியிடப்பட்ட ஆவணங்களிலிருந்து BIS Bandhu உண்மைத் தீர்மானம் செய்ய முடியாது. மேலும் குறிப்பிட்ட கேள்வியைக் கேளுங்கள் அல்லது அதிகாரப்பூர்வ BIS சேவையைப் பயன்படுத்துங்கள்.', finder: 'தயாரிப்பு → தரநிலை கண்டறிதல்', applicability: 'பொருந்துதல் சரிபார்ப்பு', guide: 'சான்றிதழ் வழிகாட்டி', journey: 'சான்றிதழ் பயணம்', checklist: 'ஆவணப் பட்டியல்', labs: 'சோதனை ஆய்வகங்கள்', consumers: 'நுகர்வோர் மையம்', verifyProduct: 'தயாரிப்பைச் சரிபார்க்கவும்', verifyLicence: 'உரிமத்தைச் சரிபார்க்கவும்', verifyHuid: 'HUID-ஐச் சரிபார்க்கவும்', complaints: 'புகார்கள்', hallmarking: 'ஹால்மார்க்கிங் தகவல்', services: 'BIS சேவைகள்', help: 'உதவி', how: 'இது எவ்வாறு செயல்படுகிறது', session: 'என் அமர்வு', demoResult: 'இந்த விளக்கத் திரை எந்த தயாரிப்பு, உரிமம், HUID, ஆய்வகம், தரநிலை அல்லது BIS நிலையைச் சரிபார்க்கவில்லை.', searchLabel: 'தயாரிப்பு, முக்கியச்சொல் அல்லது IS எண்', searchPlaceholder: 'தயாரிப்பை விவரிக்கவும் அல்லது IS எண்ணை உள்ளிடவும்', saved: 'இந்தச் சாதனத்தில் சேமிக்கப்பட்டது', delete: 'உள்ளூர் அமர்வுத் தரவை நீக்கவும்', empty: 'உள்ளூர் தேடல்கள் அல்லது பட்டியல் முன்னேற்றம் இல்லை.', checklistLead: 'இந்த உள்ளூர் தயாரிப்பு பட்டியலைப் பயன்படுத்தவும். இது அதிகாரப்பூர்வ விண்ணப்பம் அல்லது சமர்ப்பிப்பு அல்ல.', coverage: 'BIS Bandhu முழுமையான BIS பட்டியல் அல்ல. பதில்கள் இந்த முன்மாதிரிக்காக குறியிடப்பட்ட ஆவணங்களுக்கு மட்டுமே வரம்பிடப்பட்டு, ஆதாரம் இருந்தால் மூலங்களைக் காட்டும்.' },
  bn: { demo: 'ডেমো ডেটা — কেবল উদাহরণ', title: 'স্পষ্ট পরবর্তী ধাপসহ BIS পরিষেবা', lead: 'বর্তমান সূচিবদ্ধ নথি যেখানে সমর্থন করে সেখানে প্রমাণভিত্তিক নির্দেশনা ব্যবহার করুন। অন্য পরিষেবা সংশ্লিষ্ট সরকারি BIS পথ খোলে।', search: 'মান খুঁজুন', compare: 'মান তুলনা করুন', ask: 'Bandhu-কে জিজ্ঞাসা করুন', details: 'বিস্তারিত দেখুন', official: 'সরকারি BIS পরিষেবা খুলুন ↗', unavailable: 'পর্যাপ্ত সূচিবদ্ধ প্রমাণ নেই', unavailableLead: 'বর্তমান সূচিবদ্ধ নথি থেকে BIS Bandhu বাস্তব সিদ্ধান্ত দিতে পারে না। আরও নির্দিষ্ট প্রশ্ন করুন বা সরকারি BIS পরিষেবা ব্যবহার করুন।', finder: 'পণ্য → মান অনুসন্ধান', applicability: 'প্রযোজ্যতা পরীক্ষক', guide: 'সার্টিফিকেশন নির্দেশিকা', journey: 'সার্টিফিকেশন যাত্রা', checklist: 'নথির তালিকা', labs: 'পরীক্ষা পরীক্ষাগার', consumers: 'ভোক্তা কেন্দ্র', verifyProduct: 'পণ্য যাচাই করুন', verifyLicence: 'লাইসেন্স যাচাই করুন', verifyHuid: 'HUID যাচাই করুন', complaints: 'অভিযোগ', hallmarking: 'হলমার্কিং তথ্য', services: 'BIS পরিষেবা', help: 'সহায়তা', how: 'এটি কীভাবে কাজ করে', session: 'আমার সেশন', demoResult: 'এই উদাহরণ স্ক্রিন কোনও পণ্য, লাইসেন্স, HUID, পরীক্ষাগার, মান বা BIS স্থিতি যাচাই করেনি।', searchLabel: 'পণ্য, কীওয়ার্ড বা IS নম্বর', searchPlaceholder: 'পণ্যের বর্ণনা দিন বা IS নম্বর লিখুন', saved: 'এই ডিভাইসে সংরক্ষিত', delete: 'স্থানীয় সেশন ডেটা মুছুন', empty: 'এখনও কোনও স্থানীয় অনুসন্ধান বা তালিকার অগ্রগতি নেই।', checklistLead: 'এই স্থানীয় প্রস্তুতি তালিকা ব্যবহার করুন। এটি সরকারি আবেদন বা জমা নয়।', coverage: 'BIS Bandhu সম্পূর্ণ BIS তালিকা নয়। উত্তর এই প্রোটোটাইপের সূচিবদ্ধ নথিতে সীমিত এবং প্রমাণ থাকলে উৎস দেখায়।' },
};

const detailCopy = {
  en: { catalogueFilter: 'Filter demo catalogue', cataloguePlaceholder: 'Filter illustrative records', addCompare: 'Add to comparison', noCatalogue: 'No illustrative catalogue records match this filter.', scope: 'Scope', status: 'Status', source: 'Source', field: 'Field', verifiedSource: 'Verified source', chooseTwo: 'Choose two illustrative records before comparing them.', clearComparison: 'Clear comparison', workflowNotice: 'This workflow is a local guide only. It does not submit or approve a BIS application.', checklist: ['Product description', 'Applicable evidence reviewed', 'Source PDF opened', 'Questions for BIS prepared'], labFilter: 'Filter demo laboratories', labPlaceholder: 'Filter illustrative laboratories', labName: 'Illustrative laboratory listing', noLabs: 'No illustrative laboratories match this filter.', lookupPlaceholder: 'Enter a code to see an illustrative result', enteredCode: 'Entered demonstration code', noSubmission: 'There is no submission or verification service in BIS Bandhu.', serviceSearch: 'Search with Bandhu', noLocalRecord: 'No local standard record is shown unless a live answer cites evidence.', nothingSaved: 'Nothing has been saved on this device yet.', helpBody: 'Ask an evidence-backed question. Open the cited document and page before relying on a result. Use the Compliance Wizard for a conditional, informational Passport.', checklistCount: 'items completed', demoCooking: 'Illustrative cooking appliance standard', demoCookingScope: 'Sample catalogue card; not a verified BIS record.', demoLighting: 'Illustrative lighting product standard', demoLightingScope: 'Sample comparison field; not a verified BIS record.' },
  hi: { catalogueFilter: 'डेमो कैटलॉग छानें', cataloguePlaceholder: 'उदाहरण रिकॉर्ड छानें', addCompare: 'तुलना में जोड़ें', noCatalogue: 'इस फ़िल्टर से कोई उदाहरण कैटलॉग रिकॉर्ड नहीं मिलता।', scope: 'दायरा', status: 'स्थिति', source: 'स्रोत', field: 'क्षेत्र', verifiedSource: 'सत्यापित स्रोत', chooseTwo: 'तुलना से पहले दो उदाहरण रिकॉर्ड चुनें।', clearComparison: 'तुलना साफ़ करें', workflowNotice: 'यह कार्यप्रवाह केवल स्थानीय मार्गदर्शिका है। यह BIS आवेदन जमा या स्वीकृत नहीं करता।', checklist: ['उत्पाद विवरण', 'लागू साक्ष्य की समीक्षा', 'स्रोत PDF खोला गया', 'BIS के लिए प्रश्न तैयार'], labFilter: 'डेमो प्रयोगशालाएँ छानें', labPlaceholder: 'उदाहरण प्रयोगशालाएँ छानें', labName: 'उदाहरण प्रयोगशाला सूची', noLabs: 'इस फ़िल्टर से कोई उदाहरण प्रयोगशाला नहीं मिलती।', lookupPlaceholder: 'उदाहरण परिणाम के लिए कोड दर्ज करें', enteredCode: 'दर्ज किया गया डेमो कोड', noSubmission: 'BIS Bandhu में कोई आवेदन या सत्यापन सेवा नहीं है।', serviceSearch: 'Bandhu से खोजें', noLocalRecord: 'लाइव उत्तर में साक्ष्य होने तक कोई स्थानीय मानक रिकॉर्ड नहीं दिखाया जाता।', nothingSaved: 'इस डिवाइस पर अभी कुछ सहेजा नहीं गया है।', helpBody: 'साक्ष्य-आधारित प्रश्न पूछें। परिणाम पर भरोसा करने से पहले उद्धृत दस्तावेज़ और पृष्ठ खोलें। सशर्त, सूचनात्मक पासपोर्ट के लिए अनुपालन सहायक का उपयोग करें।', checklistCount: 'आइटम पूरे हुए', demoCooking: 'उदाहरण रसोई उपकरण मानक', demoCookingScope: 'नमूना कैटलॉग कार्ड; सत्यापित BIS रिकॉर्ड नहीं।', demoLighting: 'उदाहरण प्रकाश उत्पाद मानक', demoLightingScope: 'नमूना तुलना क्षेत्र; सत्यापित BIS रिकॉर्ड नहीं।' },
  mr: { catalogueFilter: 'डेमो कॅटलॉग फिल्टर करा', cataloguePlaceholder: 'उदाहरण नोंदी फिल्टर करा', addCompare: 'तुलनेत जोडा', noCatalogue: 'या फिल्टरशी जुळणाऱ्या उदाहरण कॅटलॉग नोंदी नाहीत.', scope: 'व्याप्ती', status: 'स्थिती', source: 'स्रोत', field: 'क्षेत्र', verifiedSource: 'सत्यापित स्रोत', chooseTwo: 'तुलनेपूर्वी दोन उदाहरण नोंदी निवडा.', clearComparison: 'तुलना साफ करा', workflowNotice: 'हा कार्यप्रवाह केवळ स्थानिक मार्गदर्शक आहे. तो BIS अर्ज सादर किंवा मंजूर करत नाही.', checklist: ['उत्पादन वर्णन', 'लागू पुराव्याचा आढावा', 'स्रोत PDF उघडला', 'BIS साठी प्रश्न तयार'], labFilter: 'डेमो प्रयोगशाळा फिल्टर करा', labPlaceholder: 'उदाहरण प्रयोगशाळा फिल्टर करा', labName: 'उदाहरण प्रयोगशाळा सूची', noLabs: 'या फिल्टरशी जुळणाऱ्या उदाहरण प्रयोगशाळा नाहीत.', lookupPlaceholder: 'उदाहरण निकालासाठी कोड टाका', enteredCode: 'टाकलेला डेमो कोड', noSubmission: 'BIS Bandhu मध्ये अर्ज किंवा पडताळणी सेवा नाही.', serviceSearch: 'Bandhu कडून शोधा', noLocalRecord: 'लाइव्ह उत्तरात पुरावा नसल्यास स्थानिक मानक नोंद दाखवली जात नाही.', nothingSaved: 'या उपकरणावर अजून काही जतन केलेले नाही.', helpBody: 'पुरावा-आधारित प्रश्न विचारा. निकालावर अवलंबून राहण्यापूर्वी उद्धृत दस्तऐवज आणि पान उघडा. सशर्त, माहितीपर पासपोर्टसाठी अनुपालन सहाय्यक वापरा.', checklistCount: 'घटक पूर्ण झाले', demoCooking: 'उदाहरण स्वयंपाक उपकरण मानक', demoCookingScope: 'नमुना कॅटलॉग कार्ड; सत्यापित BIS नोंद नाही.', demoLighting: 'उदाहरण प्रकाश उत्पादन मानक', demoLightingScope: 'नमुना तुलना क्षेत्र; सत्यापित BIS नोंद नाही.' },
  ta: { catalogueFilter: 'டெமோ பட்டியலை வடிகட்டவும்', cataloguePlaceholder: 'விளக்கப் பதிவுகளை வடிகட்டவும்', addCompare: 'ஒப்பீட்டில் சேர்க்கவும்', noCatalogue: 'இந்த வடிகட்டலுக்கு விளக்கப் பட்டியல் பதிவுகள் இல்லை.', scope: 'வரம்பு', status: 'நிலை', source: 'மூலம்', field: 'புலம்', verifiedSource: 'சரிபார்க்கப்பட்ட மூலம்', chooseTwo: 'ஒப்பிடுவதற்கு முன் இரண்டு விளக்கப் பதிவுகளைத் தேர்ந்தெடுக்கவும்.', clearComparison: 'ஒப்பீட்டை அழிக்கவும்', workflowNotice: 'இந்தப் பணிப்பாய்வு உள்ளூர் வழிகாட்டி மட்டுமே. இது BIS விண்ணப்பத்தைச் சமர்ப்பிக்கவோ அங்கீகரிக்கவோாது.', checklist: ['தயாரிப்பு விளக்கம்', 'பொருந்தும் ஆதாரம் மதிப்பாய்வு', 'மூல PDF திறக்கப்பட்டது', 'BIS-க்கான கேள்விகள் தயார்'], labFilter: 'டெமோ ஆய்வகங்களை வடிகட்டவும்', labPlaceholder: 'விளக்க ஆய்வகங்களை வடிகட்டவும்', labName: 'விளக்க ஆய்வகப் பட்டியல்', noLabs: 'இந்த வடிகட்டலுக்கு விளக்க ஆய்வகங்கள் இல்லை.', lookupPlaceholder: 'விளக்க முடிவிற்கு குறியீட்டை உள்ளிடவும்', enteredCode: 'உள்ளிட்ட டெமோ குறியீடு', noSubmission: 'BIS Bandhu-வில் விண்ணப்பம் அல்லது சரிபார்ப்பு சேவை இல்லை.', serviceSearch: 'Bandhu மூலம் தேடுக', noLocalRecord: 'நேரடி பதிலில் ஆதாரம் இருக்கும் வரை உள்ளூர் தரநிலை பதிவு காட்டப்படாது.', nothingSaved: 'இந்தச் சாதனத்தில் இன்னும் எதுவும் சேமிக்கப்படவில்லை.', helpBody: 'ஆதார-அடிப்படையிலான கேள்வியைக் கேளுங்கள். முடிவை நம்புவதற்கு முன் மேற்கோள் ஆவணம் மற்றும் பக்கத்தைத் திறக்கவும். நிபந்தனை தகவல் பாஸ்போர்டுக்கு இணக்க உதவியாளரைப் பயன்படுத்தவும்.', checklistCount: 'உருப்படிகள் முடிந்தன', demoCooking: 'விளக்க சமையல் சாதனத் தரநிலை', demoCookingScope: 'மாதிரி பட்டியல் அட்டை; சரிபார்க்கப்பட்ட BIS பதிவு அல்ல.', demoLighting: 'விளக்க ஒளி தயாரிப்புத் தரநிலை', demoLightingScope: 'மாதிரி ஒப்பீட்டுப் புலம்; சரிபார்க்கப்பட்ட BIS பதிவு அல்ல.' },
  bn: { catalogueFilter: 'ডেমো ক্যাটালগ ফিল্টার করুন', cataloguePlaceholder: 'উদাহরণ রেকর্ড ফিল্টার করুন', addCompare: 'তুলনায় যোগ করুন', noCatalogue: 'এই ফিল্টারের সঙ্গে মেলে এমন উদাহরণ ক্যাটালগ রেকর্ড নেই।', scope: 'পরিধি', status: 'স্থিতি', source: 'উৎস', field: 'ক্ষেত্র', verifiedSource: 'যাচাইকৃত উৎস', chooseTwo: 'তুলনার আগে দুটি উদাহরণ রেকর্ড বেছে নিন।', clearComparison: 'তুলনা পরিষ্কার করুন', workflowNotice: 'এই কর্মপ্রবাহ কেবল স্থানীয় নির্দেশিকা। এটি BIS আবেদন জমা বা অনুমোদন করে না।', checklist: ['পণ্যের বিবরণ', 'প্রযোজ্য প্রমাণ পর্যালোচনা', 'উৎস PDF খোলা হয়েছে', 'BIS-এর জন্য প্রশ্ন প্রস্তুত'], labFilter: 'ডেমো পরীক্ষাগার ফিল্টার করুন', labPlaceholder: 'উদাহরণ পরীক্ষাগার ফিল্টার করুন', labName: 'উদাহরণ পরীক্ষাগার তালিকা', noLabs: 'এই ফিল্টারের সঙ্গে মেলে এমন উদাহরণ পরীক্ষাগার নেই।', lookupPlaceholder: 'উদাহরণ ফলাফলের জন্য কোড লিখুন', enteredCode: 'দেওয়া ডেমো কোড', noSubmission: 'BIS Bandhu-তে আবেদন বা যাচাই পরিষেবা নেই।', serviceSearch: 'Bandhu দিয়ে খুঁজুন', noLocalRecord: 'লাইভ উত্তরে প্রমাণ না থাকলে স্থানীয় মানের রেকর্ড দেখানো হয় না।', nothingSaved: 'এই ডিভাইসে এখনও কিছু সংরক্ষিত নেই।', helpBody: 'প্রমাণভিত্তিক প্রশ্ন করুন। ফলাফলের উপর নির্ভর করার আগে উদ্ধৃত নথি ও পৃষ্ঠা খুলুন। শর্তযুক্ত তথ্যভিত্তিক পাসপোর্টের জন্য কমপ্লায়েন্স সহায়ক ব্যবহার করুন।', checklistCount: 'আইটেম সম্পন্ন', demoCooking: 'উদাহরণ রান্নার যন্ত্রের মান', demoCookingScope: 'নমুনা ক্যাটালগ কার্ড; যাচাইকৃত BIS রেকর্ড নয়।', demoLighting: 'উদাহরণ আলো পণ্যের মান', demoLightingScope: 'নমুনা তুলনা ক্ষেত্র; যাচাইকৃত BIS রেকর্ড নয়।' },
};

const storageKey = 'bis-bandhu-reference-session';
type Local = { saved: string[]; checklist: Record<string, boolean> };
const read = (): Local => { try { return { saved: [], checklist: {}, ...JSON.parse(localStorage.getItem(storageKey) || '{}') }; } catch { return { saved: [], checklist: {} }; } };
const save = (value: Local) => { try { localStorage.setItem(storageKey, JSON.stringify(value)); } catch { /* local storage is optional */ } };
function Demo({ children }: { children?: ReactNode }) { const { language } = useLanguage(); return <span className="demo-badge">{copy[language].demo}{children}</span>; }
function Official({ href, children }: { href: string; children: ReactNode }) { return <a className="official-service-link" href={href} target="_blank" rel="noopener noreferrer">{children}</a>; }

export function ReferencePages({ page, navigate, ask, openWizard, openAudience }: Props) {
  const { language } = useLanguage(); const text = copy[language];
  const detail = detailCopy[language];
  const demoStandards = [
    { id: 'demo-cooking', name: detail.demoCooking, scope: detail.demoCookingScope },
    { id: 'demo-lighting', name: detail.demoLighting, scope: detail.demoLightingScope },
  ];
  const [query, setQuery] = useState(''); const [session, setSession] = useState<Local>(read);
  const [catalogueQuery, setCatalogueQuery] = useState(''); const [selected, setSelected] = useState<string[]>([]);
  const [labQuery, setLabQuery] = useState(''); const [lookup, setLookup] = useState(''); const [lookupSubmitted, setLookupSubmitted] = useState(false);
  useEffect(() => { setSession(read()); }, [page]);
  const persist = (next: Local) => { setSession(next); save(next); try { localStorage.setItem('bis-bandhu-service-session', JSON.stringify({ searches: next.saved, checklist: next.checklist })); } catch { /* local storage is optional */ } };
  const toAssistant = (event: FormEvent, audience: Audience = 'general') => { event.preventDefault(); const value = query.trim(); if (!value) return; persist({ ...session, saved: [value, ...session.saved.filter(x => x !== value)].slice(0, 10) }); ask(value, audience); };
  const title: Record<ReferencePage, string> = { standards: text.search, 'standard-detail': text.details, compare: text.compare, finder: text.finder, applicability: text.applicability, 'certification-guide': text.guide, 'certification-journey': text.journey, checklist: text.checklist, labs: text.labs, 'lab-detail': text.labs, consumers: text.consumers, 'verify-product': text.verifyProduct, 'verify-licence': text.verifyLicence, 'verify-huid': text.verifyHuid, complaints: text.complaints, hallmarking: text.hallmarking, services: text.services, help: text.help, 'how-it-works': text.how, session: text.session };
  const nav = (target: ReferencePage, label: string) => <button className="reference-link" onClick={() => navigate(target)}>{label}<span aria-hidden="true">→</span></button>;
  const search = <form className="reference-search" onSubmit={toAssistant}><label htmlFor="reference-search">{text.searchLabel}</label><div><input id="reference-search" value={query} onChange={event => setQuery(event.target.value)} maxLength={1000} placeholder={text.searchPlaceholder}/><button>{text.ask}</button></div></form>;
  const manufacturerSearch = <form className="reference-search" onSubmit={event => toAssistant(event, 'manufacturer')}><label htmlFor="reference-search">{text.searchLabel}</label><div><input id="reference-search" value={query} onChange={event => setQuery(event.target.value)} maxLength={1000} placeholder={text.searchPlaceholder}/><button>{text.ask}</button></div></form>;
  const unavailable = <section className="evidence-limited reference-limit" role="note"><h2>{text.unavailable}</h2><p>{text.unavailableLead}</p><Official href={official.standards}>{text.official}</Official></section>;
  const cards = (items: Array<[string, ReferencePage, string]>) => <div className="reference-card-grid">{items.map(([label, target, description]) => <article className="reference-card" key={target}><h2>{label}</h2><p>{description}</p>{nav(target, text.details)}</article>)}</div>;
  const toggleSelected = (id: string) => setSelected(current => current.includes(id) ? current.filter(value => value !== id) : [...current, id].slice(0, 2));

  if (page === 'standards') { const filtered=demoStandards.filter(record => `${record.name} ${record.scope}`.toLowerCase().includes(catalogueQuery.toLowerCase())); return <section className="reference-page"><header className="reference-intro"><p className="eyebrow">{text.services}</p><h1>{text.search}</h1><p>{text.coverage}</p></header>{search}<label className="reference-filter">{detail.catalogueFilter}<input value={catalogueQuery} onChange={event=>setCatalogueQuery(event.target.value)} placeholder={detail.cataloguePlaceholder}/></label><div className="reference-card-grid">{filtered.map(record => <article className="reference-card" key={record.id}><Demo/><h2>{record.name}</h2><p>{record.scope}</p><label><input type="checkbox" aria-label={`${detail.addCompare}: ${record.name}`} checked={selected.includes(record.id)} onChange={()=>toggleSelected(record.id)}/> {detail.addCompare}</label>{nav('standard-detail', text.details)}</article>)}</div>{!filtered.length&&<p className="reference-copy">{detail.noCatalogue}</p>}{unavailable}<div className="reference-actions"><button disabled={selected.length<2} onClick={()=>navigate('compare')}>{text.compare} ({selected.length}/2)</button><Official href={official.standards}>{text.official}</Official></div></section>; }
  if (page === 'standard-detail') return <section className="reference-page"><header className="reference-intro"><Demo/><h1>{demoStandards[0].name}</h1><p>{demoStandards[0].scope}</p></header><dl className="reference-details"><dt>{detail.scope}</dt><dd>{demoStandards[0].scope}</dd><dt>{detail.status}</dt><dd><Demo/></dd><dt>{detail.source}</dt><dd>{text.unavailable}</dd></dl>{unavailable}<div className="reference-actions">{nav('standards', text.search)}{nav('compare', text.compare)}</div></section>;
  if (page === 'compare') { const comparing=demoStandards.filter(record=>selected.includes(record.id)); return <section className="reference-page"><header className="reference-intro"><p className="eyebrow">{text.services}</p><h1>{text.compare}</h1><p>{text.coverage}</p></header>{comparing.length===2 ? <div className="comparison-table"><div><b>{detail.field}</b><b>{comparing[0].name}</b><b>{comparing[1].name}</b></div><div><span>{detail.status}</span><Demo/><Demo/></div><div><span>{detail.scope}</span><span>{comparing[0].scope}</span><span>{comparing[1].scope}</span></div><div><span>{detail.verifiedSource}</span><span>{text.unavailable}</span><span>{text.unavailable}</span></div></div> : <p className="reference-copy">{detail.chooseTwo}</p>}<div className="reference-actions">{demoStandards.map(record=><label key={record.id}><input type="checkbox" checked={selected.includes(record.id)} onChange={()=>toggleSelected(record.id)}/>{record.name}</label>)}<button className="secondary" onClick={()=>setSelected([])}>{detail.clearComparison}</button></div>{search}</section>; }
  if (page === 'finder' || page === 'applicability') return <section className="reference-page"><header className="reference-intro"><p className="eyebrow">{text.services}</p><h1>{title[page]}</h1><p>{page === 'finder' ? text.coverage : text.unavailableLead}</p></header>{manufacturerSearch}{unavailable}<div className="reference-actions">{nav('certification-guide', text.guide)}<button onClick={openWizard}>{text.journey}</button></div></section>;
  if (page === 'certification-guide' || page === 'certification-journey') return <section className="reference-page"><header className="reference-intro"><p className="eyebrow">{text.services}</p><h1>{title[page]}</h1><p>{text.checklistLead}</p></header><ol className="workflow-pipeline"><li>1 <span>{text.finder}</span></li><li>2 <span>{text.applicability}</span></li><li>3 <span>{text.checklist}</span></li><li>4 <span>{text.journey}</span></li></ol><Demo/><p className="reference-copy">{detail.workflowNotice}</p><div className="reference-actions"><button onClick={openWizard}>{text.journey}</button>{nav('checklist', text.checklist)}<Official href={official.certification}>{text.official}</Official></div></section>;
  if (page === 'checklist') { return <section className="reference-page"><header className="reference-intro"><h1>{text.checklist}</h1><p>{text.checklistLead}</p></header><div className="local-checklist">{detail.checklist.map((entry,index) => <label key={index}><input type="checkbox" checked={!!session.checklist[String(index)]} onChange={() => persist({ ...session, checklist: { ...session.checklist, [index]: !session.checklist[String(index)] } })}/><span>{entry}</span></label>)}</div><p className="reference-copy">{text.saved}</p></section>; }
  if (page === 'labs' || page === 'lab-detail') { const laboratory=detail.labName; const visible=laboratory.toLowerCase().includes(labQuery.toLowerCase()); return <section className="reference-page"><header className="reference-intro"><p className="eyebrow">{text.services}</p><h1>{title[page]}</h1><p>{text.demoResult}</p></header>{page==='labs'&&<label className="reference-filter">{detail.labFilter}<input value={labQuery} onChange={event=>setLabQuery(event.target.value)} placeholder={detail.labPlaceholder}/></label>}{visible?<article className="reference-card"><Demo/><h2>{laboratory}</h2><p>{text.demoResult}</p>{page === 'labs' && nav('lab-detail', text.details)}</article>:<p className="reference-copy">{detail.noLabs}</p>}{page === 'lab-detail' && <div className="reference-actions">{nav('labs', text.labs)}</div>}<Official href={official.labs}>{text.official}</Official></section>; }
  if (page === 'consumers') return <section className="reference-page"><header className="reference-intro"><p className="eyebrow">{text.services}</p><h1>{text.consumers}</h1><p>{text.coverage}</p></header>{cards([[text.verifyProduct, 'verify-product', text.demoResult], [text.verifyLicence, 'verify-licence', text.demoResult], [text.verifyHuid, 'verify-huid', text.demoResult], [text.complaints, 'complaints', text.unavailableLead], [text.hallmarking, 'hallmarking', text.unavailableLead]])}<div className="reference-actions"><button onClick={() => openAudience('consumer')}>{text.ask}</button><Official href={official.consumer}>{text.official}</Official></div></section>;
  if (page === 'verify-product' || page === 'verify-licence' || page === 'verify-huid') return <section className="reference-page"><header className="reference-intro"><Demo/><h1>{title[page]}</h1><p>{text.demoResult}</p></header><form className="reference-search" onSubmit={event => { event.preventDefault(); setLookupSubmitted(!!lookup.trim()); }}><label htmlFor="lookup">{title[page]}</label><div><input id="lookup" value={lookup} onChange={event=>setLookup(event.target.value)} maxLength={1000} placeholder={detail.lookupPlaceholder}/><button type="submit">{text.details}</button></div></form>{lookupSubmitted&&<section className="demo-result" role="status"><Demo/><p>{text.demoResult}</p><p>{detail.enteredCode}: {lookup}</p></section>}<Official href={official.care}>{text.official}</Official></section>;
  if (page === 'complaints' || page === 'hallmarking') return <section className="reference-page"><header className="reference-intro"><h1>{title[page]}</h1><p>{text.unavailableLead}</p></header><section className="reference-limit"><p>{detail.noSubmission}</p><Official href={page === 'complaints' ? official.complaints : official.hallmarking}>{text.official}</Official></section></section>;
  if (page === 'services') return <section className="reference-page"><header className="reference-intro"><p className="eyebrow">BIS Bandhu</p><h1>{text.title}</h1><p>{text.lead}</p></header><form className="reference-search" onSubmit={toAssistant}><label htmlFor="service-search">{text.searchLabel}</label><div><input id="service-search" value={query} onChange={event => setQuery(event.target.value)} maxLength={1000} placeholder={text.searchPlaceholder}/><button>{detail.serviceSearch}</button></div></form><p className="evidence-limited">{detail.noLocalRecord}</p>{session.saved.length ? <section className="reference-copy"><h2>{text.saved}</h2>{session.saved.map(item => <button className="reference-link" key={item} onClick={() => ask(item, 'general')}>{item}</button>)}</section> : <p className="reference-copy">{detail.nothingSaved}</p>}{cards([[text.search, 'standards', text.coverage], [text.finder, 'finder', text.coverage], [text.consumers, 'consumers', text.demoResult], [text.guide, 'certification-guide', text.checklistLead], [text.help, 'help', text.coverage], [text.session, 'session', text.saved]])}<section className="reference-directory" aria-label={text.services}><h2>{text.services}</h2><div>{['compare','applicability','certification-journey','checklist','labs','verify-product','verify-licence','verify-huid','complaints','hallmarking','how-it-works'].map(target => <button className="reference-link" key={target} onClick={() => navigate(target as ReferencePage)}>{title[target as ReferencePage]} <span aria-hidden="true">→</span></button>)}</div></section><button className="secondary" onClick={() => { try { localStorage.removeItem(storageKey); localStorage.removeItem('bis-bandhu-service-session'); } catch { /* optional */ } setSession({ saved: [], checklist: {} }); }}>{text.delete}</button></section>;
  if (page === 'help' || page === 'how-it-works') return <section className="reference-page"><header className="reference-intro"><h1>{title[page]}</h1><p>{text.coverage}</p></header><div className="reference-copy"><h2>{text.ask}</h2><p>{detail.helpBody}</p><h2>{text.unavailable}</h2><p>{text.unavailableLead}</p></div></section>;
  if (page === 'session') return <section className="reference-page"><header className="reference-intro"><h1>{text.session}</h1><p>{text.saved}</p></header><div className="reference-copy"><h2>{text.search}</h2>{session.saved.length ? <ul>{session.saved.map(item => <li key={item}>{item}</li>)}</ul> : <p>{text.empty}</p>}<h2>{text.checklist}</h2><p>{Object.values(session.checklist).filter(Boolean).length || 0} {detail.checklistCount}</p></div><button className="secondary" onClick={() => { try { localStorage.removeItem(storageKey); } catch { /* optional */ } setSession({ saved: [], checklist: {} }); }}>{text.delete}</button></section>;
  return <section className="reference-page"><header className="reference-intro"><p className="eyebrow">BIS Bandhu</p><h1>{text.title}</h1><p>{text.lead}</p></header>{cards([[text.search, 'standards', text.coverage], [text.finder, 'finder', text.coverage], [text.consumers, 'consumers', text.demoResult], [text.guide, 'certification-guide', text.checklistLead], [text.help, 'help', text.coverage], [text.session, 'session', text.saved]])}</section>;
}
