import { FormEvent, useState } from 'react';
import type { Audience } from '../types/chat';
import { useLanguage } from '../i18n/LanguageContext';
import type { Language } from '../i18n/translations';

type ServiceCopy = {
  kicker: string; title: string; lead: string; standards: string; industry: string; consumers: string;
  standardsLead: string; finderLabel: string; finderPlaceholder: string; search: string; compare: string;
  evidenceNote: string; officialStandards: string; certification: string; checklist: string; labs: string;
  consumerHelp: string; verification: string; hallmarking: string; official: string; help: string;
  howItWorks: string; session: string; recentQuestions: string; savedSearches: string; clear: string;
  empty: string; consumerNote: string;
};

const copy: Record<Language, ServiceCopy> = {
  en: { kicker: 'BIS services', title: 'Choose a useful next step', lead: 'BIS Bandhu explains only from indexed evidence. Official links open the relevant BIS service; they do not verify or submit anything here.', standards: 'Standards', industry: 'For industry', consumers: 'For consumers', standardsLead: 'Search a product, keyword, or IS number against the evidence-backed Assistant.', finderLabel: 'Product, keyword, or IS number', finderPlaceholder: 'Describe a product or enter an IS number', search: 'Search with Bandhu', compare: 'Compare terms', evidenceNote: 'No local standard record is shown unless a live answer cites evidence. Use the official search for the complete catalogue.', officialStandards: 'Open official BIS standards search', certification: 'Certification guide', checklist: 'My preparation checklist', labs: 'Find official laboratory information', consumerHelp: 'Consumer help and complaints', verification: 'Verify product, licence or HUID in BIS CARE', hallmarking: 'Hallmarking information', official: 'Open official BIS service ↗', help: 'How it works', howItWorks: 'Ask a precise question. BIS Bandhu returns guidance only when the current indexed documents support it, with a source and page. For broader services, follow the official BIS handoff.', session: 'My session', recentQuestions: 'Recent questions on this device', savedSearches: 'Saved product or standard searches', clear: 'Delete local session data', empty: 'Nothing has been saved on this device yet.', consumerNote: 'BIS Bandhu does not verify a product, licence, or HUID. Use BIS CARE for that official service.' },
  hi: { kicker: 'BIS सेवाएँ', title: 'उपयोगी अगला कदम चुनें', lead: 'BIS Bandhu केवल सूचीबद्ध साक्ष्य से समझाता है। आधिकारिक लिंक संबंधित BIS सेवा खोलते हैं; यहाँ कोई सत्यापन या आवेदन नहीं होता।', standards: 'मानक', industry: 'उद्योग के लिए', consumers: 'उपभोक्ताओं के लिए', standardsLead: 'उत्पाद, कीवर्ड या IS नंबर को साक्ष्य-आधारित सहायक से खोजें।', finderLabel: 'उत्पाद, कीवर्ड या IS नंबर', finderPlaceholder: 'उत्पाद बताइए या IS नंबर दर्ज कीजिए', search: 'Bandhu से खोजें', compare: 'शब्दों की तुलना करें', evidenceNote: 'जब तक लाइव उत्तर साक्ष्य न दे, स्थानीय मानक रिकॉर्ड नहीं दिखता। पूरी सूची के लिए आधिकारिक खोज उपयोग करें।', officialStandards: 'आधिकारिक BIS मानक खोज खोलें', certification: 'प्रमाणन मार्गदर्शिका', checklist: 'मेरी तैयारी सूची', labs: 'आधिकारिक प्रयोगशाला जानकारी खोजें', consumerHelp: 'उपभोक्ता सहायता और शिकायतें', verification: 'BIS CARE में उत्पाद, लाइसेंस या HUID सत्यापित करें', hallmarking: 'हॉलमार्किंग जानकारी', official: 'आधिकारिक BIS सेवा खोलें ↗', help: 'यह कैसे काम करता है', howItWorks: 'स्पष्ट प्रश्न पूछें। BIS Bandhu केवल तब मार्गदर्शन देता है जब मौजूदा सूचीबद्ध दस्तावेज़, स्रोत और पृष्ठ उसका समर्थन करते हों। अन्य सेवाओं के लिए आधिकारिक BIS लिंक अपनाएँ।', session: 'मेरा सत्र', recentQuestions: 'इस डिवाइस के हाल के प्रश्न', savedSearches: 'सहेजे उत्पाद या मानक खोज', clear: 'स्थानीय सत्र डेटा हटाएँ', empty: 'इस डिवाइस पर अभी कुछ सहेजा नहीं गया है।', consumerNote: 'BIS Bandhu उत्पाद, लाइसेंस या HUID सत्यापित नहीं करता। इस आधिकारिक सेवा के लिए BIS CARE उपयोग करें।' },
  mr: { kicker: 'BIS सेवा', title: 'उपयुक्त पुढील पाऊल निवडा', lead: 'BIS Bandhu फक्त अनुक्रमित पुराव्यावरून माहिती देतो. अधिकृत दुवे संबंधित BIS सेवा उघडतात; येथे पडताळणी किंवा अर्ज होत नाही.', standards: 'मानके', industry: 'उद्योगासाठी', consumers: 'ग्राहकांसाठी', standardsLead: 'उत्पादन, कीवर्ड किंवा IS क्रमांक पुरावा-आधारित सहाय्यकाद्वारे शोधा.', finderLabel: 'उत्पादन, कीवर्ड किंवा IS क्रमांक', finderPlaceholder: 'उत्पादनाचे वर्णन करा किंवा IS क्रमांक टाका', search: 'Bandhu कडून शोधा', compare: 'संज्ञांची तुलना करा', evidenceNote: 'लाइव्ह उत्तर पुरावा देत नाही तोपर्यंत स्थानिक मानक नोंद दाखवली जात नाही. संपूर्ण सूचीसाठी अधिकृत शोध वापरा.', officialStandards: 'अधिकृत BIS मानक शोध उघडा', certification: 'प्रमाणन मार्गदर्शक', checklist: 'माझी तयारी सूची', labs: 'अधिकृत प्रयोगशाळा माहिती शोधा', consumerHelp: 'ग्राहक मदत आणि तक्रारी', verification: 'BIS CARE मध्ये उत्पादन, परवाना किंवा HUID तपासा', hallmarking: 'हॉलमार्किंग माहिती', official: 'अधिकृत BIS सेवा उघडा ↗', help: 'हे कसे कार्य करते', howItWorks: 'नेमका प्रश्न विचारा. विद्यमान अनुक्रमित दस्तऐवज, स्रोत आणि पान समर्थन देतात तेव्हाच BIS Bandhu मार्गदर्शन देतो. इतर सेवांसाठी अधिकृत BIS दुवा वापरा.', session: 'माझे सत्र', recentQuestions: 'या उपकरणावरील अलीकडील प्रश्न', savedSearches: 'जतन केलेले उत्पादन किंवा मानक शोध', clear: 'स्थानिक सत्र डेटा हटवा', empty: 'या उपकरणावर अजून काही जतन केलेले नाही.', consumerNote: 'BIS Bandhu उत्पादन, परवाना किंवा HUID तपासत नाही. त्या अधिकृत सेवेसाठी BIS CARE वापरा.' },
  ta: { kicker: 'BIS சேவைகள்', title: 'பயனுள்ள அடுத்த படியைத் தேர்ந்தெடுக்கவும்', lead: 'BIS Bandhu குறியிடப்பட்ட ஆதாரத்தில் மட்டுமே விளக்குகிறது. அதிகாரப்பூர்வ இணைப்புகள் தொடர்புடைய BIS சேவையைத் திறக்கும்; இங்கே சரிபார்ப்பு அல்லது விண்ணப்பம் இல்லை.', standards: 'தரநிலைகள்', industry: 'தொழில்துறைக்கு', consumers: 'நுகர்வோருக்கு', standardsLead: 'தயாரிப்பு, முக்கியச்சொல் அல்லது IS எண்ணை ஆதார-அடிப்படையிலான உதவியாளரிடம் தேடுங்கள்.', finderLabel: 'தயாரிப்பு, முக்கியச்சொல் அல்லது IS எண்', finderPlaceholder: 'தயாரிப்பை விவரிக்கவும் அல்லது IS எண்ணை உள்ளிடவும்', search: 'Bandhu-விடம் தேடு', compare: 'சொற்களை ஒப்பிடு', evidenceNote: 'நேரடி பதில் ஆதாரம் தராத வரை உள்ளூர் தரநிலைப் பதிவு காட்டப்படாது. முழுப் பட்டியலுக்கு அதிகாரப்பூர்வ தேடலைப் பயன்படுத்தவும்.', officialStandards: 'அதிகாரப்பூர்வ BIS தரநிலை தேடலைத் திறக்கவும்', certification: 'சான்றிதழ் வழிகாட்டி', checklist: 'என் தயாரிப்பு பட்டியல்', labs: 'அதிகாரப்பூர்வ ஆய்வகத் தகவலைக் கண்டறியவும்', consumerHelp: 'நுகர்வோர் உதவி மற்றும் புகார்கள்', verification: 'BIS CARE-ல் தயாரிப்பு, உரிமம் அல்லது HUID-ஐ சரிபார்க்கவும்', hallmarking: 'ஹால்மார்க்கிங் தகவல்', official: 'அதிகாரப்பூர்வ BIS சேவையைத் திறக்கவும் ↗', help: 'இது எவ்வாறு செயல்படுகிறது', howItWorks: 'துல்லியமான கேள்வியைக் கேளுங்கள். நடப்பு குறியிடப்பட்ட ஆவணங்கள் ஆதாரமும் பக்கமும் வழங்கும்போது மட்டுமே BIS Bandhu வழிகாட்டுகிறது. மற்ற சேவைகளுக்கு அதிகாரப்பூர்வ BIS இணைப்பைப் பின்பற்றவும்.', session: 'என் அமர்வு', recentQuestions: 'இந்தச் சாதனத்தின் சமீபத்திய கேள்விகள்', savedSearches: 'சேமித்த தயாரிப்பு அல்லது தரநிலைத் தேடல்கள்', clear: 'உள்ளூர் அமர்வுத் தரவை நீக்கவும்', empty: 'இந்தச் சாதனத்தில் இன்னும் எதுவும் சேமிக்கப்படவில்லை.', consumerNote: 'BIS Bandhu தயாரிப்பு, உரிமம் அல்லது HUID-ஐ சரிபார்க்காது. அதிகாரப்பூர்வ சேவைக்கு BIS CARE-ஐப் பயன்படுத்தவும்.' },
  bn: { kicker: 'BIS পরিষেবা', title: 'একটি উপযোগী পরবর্তী ধাপ বেছে নিন', lead: 'BIS Bandhu কেবল সূচিবদ্ধ প্রমাণ থেকে ব্যাখ্যা করে। সরকারি লিঙ্ক সংশ্লিষ্ট BIS পরিষেবা খোলে; এখানে কোনও যাচাই বা আবেদন হয় না।', standards: 'মান', industry: 'শিল্পের জন্য', consumers: 'ভোক্তাদের জন্য', standardsLead: 'পণ্য, কীওয়ার্ড বা IS নম্বর প্রমাণভিত্তিক সহকারীর কাছে খুঁজুন।', finderLabel: 'পণ্য, কীওয়ার্ড বা IS নম্বর', finderPlaceholder: 'পণ্যের বর্ণনা দিন বা IS নম্বর লিখুন', search: 'Bandhu-কে দিয়ে খুঁজুন', compare: 'শব্দ তুলনা করুন', evidenceNote: 'লাইভ উত্তর প্রমাণ না দিলে স্থানীয় মানের রেকর্ড দেখানো হয় না। সম্পূর্ণ তালিকার জন্য সরকারি অনুসন্ধান ব্যবহার করুন।', officialStandards: 'সরকারি BIS মান অনুসন্ধান খুলুন', certification: 'সার্টিফিকেশন নির্দেশিকা', checklist: 'আমার প্রস্তুতি তালিকা', labs: 'সরকারি পরীক্ষাগার তথ্য খুঁজুন', consumerHelp: 'ভোক্তা সহায়তা ও অভিযোগ', verification: 'BIS CARE-এ পণ্য, লাইসেন্স বা HUID যাচাই করুন', hallmarking: 'হলমার্কিং তথ্য', official: 'সরকারি BIS পরিষেবা খুলুন ↗', help: 'এটি কীভাবে কাজ করে', howItWorks: 'নির্দিষ্ট প্রশ্ন করুন। বর্তমান সূচিবদ্ধ নথি উৎস ও পৃষ্ঠা দিয়ে সমর্থন করলেই BIS Bandhu নির্দেশনা দেয়। অন্য পরিষেবার জন্য সরকারি BIS লিঙ্ক অনুসরণ করুন।', session: 'আমার সেশন', recentQuestions: 'এই ডিভাইসের সাম্প্রতিক প্রশ্ন', savedSearches: 'সংরক্ষিত পণ্য বা মান অনুসন্ধান', clear: 'স্থানীয় সেশন ডেটা মুছুন', empty: 'এই ডিভাইসে এখনও কিছু সংরক্ষিত নেই।', consumerNote: 'BIS Bandhu পণ্য, লাইসেন্স বা HUID যাচাই করে না। সেই সরকারি পরিষেবার জন্য BIS CARE ব্যবহার করুন।' },
};

const sessionKey = 'bis-bandhu-service-session';
type LocalSession = { searches: string[]; checklist: Record<string, boolean> };
const initialSession: LocalSession = { searches: [], checklist: {} };
const readSession = (): LocalSession => { try { return { ...initialSession, ...JSON.parse(localStorage.getItem(sessionKey) ?? '{}') }; } catch { return initialSession; } };
const writeSession = (session: LocalSession) => { try { localStorage.setItem(sessionKey, JSON.stringify(session)); } catch { /* local session is optional */ } };

function External({ href, children }: { href: string; children: React.ReactNode }) {
  return <a className="official-service-link" href={href} target="_blank" rel="noopener noreferrer">{children}</a>;
}

export function ServiceHub({ onAsk, onWizard, onAudience }: { onAsk: (question: string, audience?: Audience) => void; onWizard: () => void; onAudience: (audience: Audience) => void }) {
  const { language } = useLanguage();
  const text = copy[language];
  const [query, setQuery] = useState('');
  const [session, setSession] = useState<LocalSession>(readSession);

  const search = (event: FormEvent) => {
    event.preventDefault();
    const term = query.trim();
    if (!term) return;
    const next = { ...session, searches: [term, ...session.searches.filter(item => item !== term)].slice(0, 8) };
    writeSession(next);
    setSession(next);
    onAsk(term, 'general');
  };
  const toggle = (key: string) => setSession(current => {
    const next = { ...current, checklist: { ...current.checklist, [key]: !current.checklist[key] } };
    writeSession(next);
    return next;
  });
  const clear = () => { try { localStorage.removeItem(sessionKey); } catch { /* optional */ } setSession(initialSession); };

  return <section className="service-hub" aria-labelledby="services-heading">
    <div className="view-intro"><p className="eyebrow">{text.kicker}</p><h1 id="services-heading">{text.title}</h1><p>{text.lead}</p></div>
    <div className="service-grid">
      <article className="service-card service-card-wide"><h2>{text.standards}</h2><p>{text.standardsLead}</p><form onSubmit={search}><label htmlFor="service-search">{text.finderLabel}</label><div className="service-search"><input id="service-search" value={query} onChange={event => setQuery(event.target.value)} placeholder={text.finderPlaceholder} maxLength={1000} /><button type="submit">{text.search}</button></div></form><p className="evidence-limited" role="note">{text.evidenceNote}</p><div className="service-actions"><External href="https://standards.bis.gov.in/">{text.officialStandards} ↗</External><button className="secondary" type="button" onClick={() => query.trim() && onAsk(`Compare the available evidence for: ${query.trim()}`, 'general')}>{text.compare}</button></div></article>
      <article className="service-card"><h2>{text.industry}</h2><button onClick={() => onAudience('manufacturer')}>{text.standards}</button><button className="secondary" onClick={onWizard}>{text.certification}</button><External href="https://www.bis.gov.in/product-certification/product-certification-process/?lang=en">{text.official}</External></article>
      <article className="service-card"><h2>{text.consumers}</h2><p>{text.consumerNote}</p><button onClick={() => onAudience('consumer')}>{text.consumerHelp}</button><External href="https://www.bis.gov.in/bis-apps/?lang=en">{text.verification} ↗</External><External href="https://www.bis.gov.in/hallmarking-overview/consumer-protection/?lang=en">{text.hallmarking} ↗</External></article>
      <article className="service-card"><h2>{text.checklist}</h2>{[text.finderLabel, text.search, text.official].map(item => <label className="check-item" key={item}><input type="checkbox" checked={!!session.checklist[item]} onChange={() => toggle(item)} /> <span>{item}</span></label>)}<External href="https://www.bis.gov.in/laboratorys/list-of-bis-recognized-lab/?lang=en">{text.labs} ↗</External></article>
      <article className="service-card"><h2>{text.help}</h2><p>{text.howItWorks}</p><External href="https://www.bis.gov.in/consumer-overview/for-consumers-faq/?lang=en">{text.official}</External></article>
      <article className="service-card"><h2>{text.session}</h2><h3>{text.savedSearches}</h3>{session.searches.length ? <ul className="session-list">{session.searches.map(term => <li key={term}><button className="text-action" onClick={() => { setQuery(term); onAsk(term, 'general'); }}>{term}</button></li>)}</ul> : <p>{text.empty}</p>}<button className="secondary" onClick={clear}>{text.clear}</button></article>
    </div>
  </section>;
}
