export const translations = {
  en: {
    appTitle: 'BIS AI Assistant', appSubtitle: 'Standards and certification guidance from indexed BIS documents', languageLabel: 'Language',
    guidanceMode: 'Guidance mode', askQuestion: 'Ask a question', complianceWizard: 'Compliance Wizard',
    heroTitle: 'Practical standards guidance, with evidence', heroDescription: 'AI-generated informational guidance grounded in indexed BIS documents. Verify final compliance requirements with BIS or a qualified professional.',
    footer: 'Informational guidance only. Final compliance requirements should be verified with BIS or a qualified professional.',
    audienceLabel: 'I am a:', audienceGeneral: 'General user', audienceManufacturer: 'Manufacturer', audienceConsumer: 'Consumer',
    questionLabel: 'Ask a question about BIS toy standards', send: 'Send', sending: 'Sending…', suggestedQuestions: 'Suggested questions', startOver: 'Start over',
    statusReady: 'Backend ready', statusDegraded: 'Backend degraded', statusUnavailable: 'Backend unavailable', loading: 'Searching BIS documents and validating citations…', retry: 'Retry', updatingAnswers: 'Updating answers…',
    suggestionBattery: 'Which standard applies to a battery-operated toy?', suggestionHandmade: 'Are all handmade toys exempt?', suggestionDocuments: 'What documents are required for a new toy series?', suggestionTransition: 'What does the 2026 transition order do?',
    roleManufacturer: 'Manufacturer', roleConsumer: 'Consumer', choiceNotSure: 'Not sure', choiceBattery: 'Battery-operated', choiceMains: 'Mains-powered', choiceNonElectric: 'Non-electric', choiceUnder3: 'Under 3', choice3to8: '3 to 8', choiceOver8: 'Over 8', choiceMultiple: 'More than one age group', choiceIdentifyStandards: 'Identify applicable standards', choiceNewLicence: 'Apply for a new licence', choiceAddSeries: 'Add a new toy series', choiceExemption: 'Check a possible exemption', choiceTransition: 'Understand a transition order', choiceRoadmap: 'Build my compliance roadmap', choiceResearching: 'Researching', choicePreparing: 'Preparing an application', choiceLicensed: 'Already licensed', choiceScopeExtension: 'Adding to an existing licence',
    wizardEyebrow: 'GUIDED COMPLIANCE JOURNEY', wizardEntryTitle: 'Compliance Wizard', wizardEntryLead: 'Start with the guidance that fits you', wizardEntryDescription: 'Answer a few simple questions to receive cited BIS guidance. You can choose Not sure whenever you need to.', consumerCard: 'Understand toy standards before you buy or compare a product.', manufacturerCard: 'Build a personalized, evidence-backed compliance path for your product.', recommendedJourney: 'Recommended journey',
    stepProduct: 'Your product', stepPower: 'Power type', stepAge: 'Intended age group', stepStage: 'Current stage', stepNeed: 'What you need', helpProduct: 'Describe the toy in plain words. This helps us search the right BIS material.', helpPower: 'Choose how the toy works. If you do not know, choose Not sure.', helpAge: 'Choose the age group the toy is made for. If you do not know, choose Not sure.', helpStage: 'Tell us where you are in the process. A licence is BIS permission to make or sell covered products.', helpNeed: 'Choose the outcome you want from this short journey.', productDescription: 'Product description or type', validationProduct: 'Enter between 2 and 300 characters.', back: 'Back', continue: 'Continue', preparing: 'Preparing grounded guidance…', generate: 'Generate my guidance', stepProgress: 'Step {current} of 5', journeyLabel: 'JOURNEY', reviewAnswers: 'Review before generating', notAnswered: 'Not answered', editProduct: 'Edit product', editPower: 'Edit power type', editAge: 'Edit intended age group', editStage: 'Edit current stage', editGoal: 'Edit guidance goal',
    clarificationEyebrow: 'ONE MORE DETAIL', clarificationTitle: 'We need one more detail', clarificationDescription: 'We will not create a roadmap until the product details are clear enough.', editThisAnswer: 'Edit this answer', groundedGuidance: 'YOUR GROUNDED GUIDANCE', journeyTitle: 'Compliance journey', journeyResultAria: 'Compliance journey result', journeyDescription: 'Use the verified sources below to review the evidence behind this guidance.', downloadPrint: 'Download / Print report', downloadPrintAria: 'Download or print compliance action report', profileTitle: 'Your product profile', profileProduct: 'Product', profilePower: 'Power type', profileAge: 'Intended age group', profileStage: 'Current stage', profileGoal: 'Guidance goal', profileNote: 'User-provided details help route this guidance. They are not verified BIS evidence.', reportDisclaimer: 'This is informational guidance, not a BIS licence, certificate, legal opinion, or complete official application package.',
    evidenceNeedDetails: 'Need more details', evidenceInsufficient: 'Evidence insufficient', evidenceGrounded: 'Grounded answer', journeyApplicable: 'Applicable standards', journeyWhy: 'Why these standards apply', journeyChecklist: 'Your compliance checklist', journeyImportant: 'Important conditions', journeyNextAction: 'Recommended next action', sourcesHeading: 'Sources', verifiedSources: 'Verified sources', viewVerifiedDetails: 'View verified source details', referencedPages: 'Referenced pages in {document}', source: 'Source', page: 'Page', pages: 'Pages', pageUnavailable: 'not available', viewEvidence: 'View evidence', extractedSourceText: 'Extracted source text', openSourcePdf: 'Open source PDF', openSourcePdfAria: 'Open source PDF {filename}{page}', pdfOpenError: 'Unable to open the source PDF. Please try again.',
    printReportAria: 'Compliance Passport', printReportTitle: 'Compliance Passport', printReportSubtitle: 'Evidence-grounded informational guidance', generated: 'Generated', printProductProfile: 'Product profile', printDetail: 'Detail', printProvidedInformation: 'Provided information', printWhy: 'Why this applies', printChecklist: 'Compliance checklist', printImportant: 'Important conditions and limitations', printDocument: 'Document', printReferencedPages: 'Referenced pages', printProfileNote: 'These details were provided by the user to personalize the guidance. They are not verified BIS evidence.', printFooter: 'Verify applicable requirements with BIS or a qualified professional.',
    passportTitle: 'Compliance Passport', passportAvailable: 'Evidence-backed guidance available', passportNeedsInformation: 'Needs more information', passportNeedsVerification: 'Needs verification', passportReportId: 'Report ID', passportGenerated: 'Generated', passportLanguage: 'Selected language', passportNotice: 'Informational guidance — not a BIS certificate.', passportProductProfile: 'Product profile', passportUserProvided: 'User-provided information — not verified BIS evidence.', passportApplicable: 'Applicable standards', passportFindings: 'Evidence-backed completed findings', passportMissingProfile: 'Missing profile information', passportVerificationNeeded: 'Verification needed', passportNextActions: 'Next three actions', passportSources: 'Cited evidence', passportEvidenceVerification: 'The finalized response needs verification before it can support a compliance decision.', passportNoMissing: 'No missing profile fields are identified by this guidance.', passportNoVerification: 'No additional verification requirement is identified by this guidance.', passportNoActions: 'No evidence-backed next action is available.', saveAsPdf: 'Save as PDF / Print', saveAsPdfAria: 'Save compliance passport as PDF or print',
  },
  hi: {
    appTitle: 'बीआईएस एआई सहायक', appSubtitle: 'अनुक्रमित BIS दस्तावेज़ों से मानक और प्रमाणन मार्गदर्शन', languageLabel: 'भाषा',
    guidanceMode: 'मार्गदर्शन मोड', askQuestion: 'प्रश्न पूछें', complianceWizard: 'अनुपालन सहायक',
    heroTitle: 'साक्ष्य के साथ व्यावहारिक मानक मार्गदर्शन', heroDescription: 'अनुक्रमित BIS दस्तावेज़ों पर आधारित AI-जनित सूचनात्मक मार्गदर्शन। अंतिम अनुपालन आवश्यकताओं के लिए BIS या योग्य विशेषज्ञ से पुष्टि करें।',
    footer: 'केवल सूचनात्मक मार्गदर्शन। अंतिम अनुपालन आवश्यकताओं की पुष्टि BIS या योग्य विशेषज्ञ से करें।',
    audienceLabel: 'मैं हूँ:', audienceGeneral: 'सामान्य उपयोगकर्ता', audienceManufacturer: 'निर्माता', audienceConsumer: 'उपभोक्ता',
    questionLabel: 'BIS खिलौना मानकों के बारे में प्रश्न पूछें', send: 'भेजें', sending: 'भेजा जा रहा है…', suggestedQuestions: 'सुझाए गए प्रश्न', startOver: 'फिर से शुरू करें',
    statusReady: 'बैकएंड तैयार है', statusDegraded: 'बैकएंड सीमित है', statusUnavailable: 'बैकएंड अनुपलब्ध है', loading: 'BIS दस्तावेज़ खोजे जा रहे हैं और उद्धरण सत्यापित किए जा रहे हैं…', retry: 'पुनः प्रयास करें', updatingAnswers: 'उत्तर अपडेट किए जा रहे हैं…',
    suggestionBattery: 'बैटरी से चलने वाले खिलौने पर कौन सा मानक लागू होता है?', suggestionHandmade: 'क्या सभी हस्तनिर्मित खिलौनों को छूट है?', suggestionDocuments: 'नई खिलौना श्रृंखला के लिए किन दस्तावेज़ों की आवश्यकता है?', suggestionTransition: '2026 का संक्रमण आदेश क्या करता है?',
    roleManufacturer: 'निर्माता', roleConsumer: 'उपभोक्ता', choiceNotSure: 'निश्चित नहीं', choiceBattery: 'बैटरी से चलने वाला', choiceMains: 'मुख्य बिजली से चलने वाला', choiceNonElectric: 'गैर-विद्युत', choiceUnder3: '3 वर्ष से कम', choice3to8: '3 से 8', choiceOver8: '8 वर्ष से अधिक', choiceMultiple: 'एक से अधिक आयु वर्ग', choiceIdentifyStandards: 'लागू मानक पहचानें', choiceNewLicence: 'नए लाइसेंस के लिए आवेदन करें', choiceAddSeries: 'नई खिलौना श्रृंखला जोड़ें', choiceExemption: 'संभावित छूट जाँचें', choiceTransition: 'संक्रमण आदेश समझें', choiceRoadmap: 'अनुपालन रोडमैप बनाएँ', choiceResearching: 'जानकारी जुटा रहे हैं', choicePreparing: 'आवेदन तैयार कर रहे हैं', choiceLicensed: 'पहले से लाइसेंस प्राप्त', choiceScopeExtension: 'मौजूदा लाइसेंस में जोड़ रहे हैं',
    wizardEyebrow: 'निर्देशित अनुपालन यात्रा', wizardEntryTitle: 'अनुपालन सहायक', wizardEntryLead: 'आपके लिए उपयुक्त मार्गदर्शन से शुरू करें', wizardEntryDescription: 'उद्धृत BIS मार्गदर्शन पाने के लिए कुछ सरल प्रश्नों के उत्तर दें। जरूरत होने पर आप निश्चित नहीं चुन सकते हैं।', consumerCard: 'खरीदने या उत्पाद की तुलना करने से पहले खिलौना मानकों को समझें।', manufacturerCard: 'अपने उत्पाद के लिए व्यक्तिगत, साक्ष्य-समर्थित अनुपालन मार्ग बनाएँ।', recommendedJourney: 'अनुशंसित यात्रा',
    stepProduct: 'आपका उत्पाद', stepPower: 'बिजली का प्रकार', stepAge: 'निर्धारित आयु वर्ग', stepStage: 'वर्तमान चरण', stepNeed: 'आपको क्या चाहिए', helpProduct: 'खिलौने का सादे शब्दों में वर्णन करें। इससे हमें सही BIS सामग्री खोजने में मदद मिलती है।', helpPower: 'खिलौना कैसे काम करता है चुनें। पता न हो तो निश्चित नहीं चुनें।', helpAge: 'खिलौना किस आयु वर्ग के लिए है चुनें। पता न हो तो निश्चित नहीं चुनें।', helpStage: 'हमें बताएं कि आप प्रक्रिया में कहाँ हैं। लाइसेंस, उत्पाद बनाने या बेचने की BIS अनुमति है।', helpNeed: 'इस छोटी यात्रा से जो परिणाम चाहते हैं उसे चुनें।', productDescription: 'उत्पाद विवरण या प्रकार', validationProduct: '2 से 300 वर्ण दर्ज करें।', back: 'पीछे', continue: 'जारी रखें', preparing: 'साक्ष्य-आधारित मार्गदर्शन तैयार हो रहा है…', generate: 'मेरा मार्गदर्शन बनाएँ', stepProgress: 'चरण {current} / 5', journeyLabel: 'यात्रा', reviewAnswers: 'बनाने से पहले उत्तरों की समीक्षा करें', notAnswered: 'उत्तर नहीं दिया', editProduct: 'उत्पाद संपादित करें', editPower: 'बिजली का प्रकार संपादित करें', editAge: 'आयु वर्ग संपादित करें', editStage: 'वर्तमान चरण संपादित करें', editGoal: 'मार्गदर्शन लक्ष्य संपादित करें',
    clarificationEyebrow: 'एक और विवरण', clarificationTitle: 'हमें एक और विवरण चाहिए', clarificationDescription: 'उत्पाद विवरण पर्याप्त स्पष्ट होने तक हम रोडमैप नहीं बनाएँगे।', editThisAnswer: 'यह उत्तर संपादित करें', groundedGuidance: 'आपका साक्ष्य-आधारित मार्गदर्शन', journeyTitle: 'अनुपालन यात्रा', journeyResultAria: 'अनुपालन यात्रा परिणाम', journeyDescription: 'इस मार्गदर्शन के साक्ष्य की समीक्षा के लिए नीचे सत्यापित स्रोतों का उपयोग करें।', downloadPrint: 'डाउनलोड / प्रिंट रिपोर्ट', downloadPrintAria: 'अनुपालन कार्य रिपोर्ट डाउनलोड या प्रिंट करें', profileTitle: 'आपकी उत्पाद प्रोफ़ाइल', profileProduct: 'उत्पाद', profilePower: 'बिजली का प्रकार', profileAge: 'निर्धारित आयु वर्ग', profileStage: 'वर्तमान चरण', profileGoal: 'मार्गदर्शन लक्ष्य', profileNote: 'उपयोगकर्ता द्वारा दिए गए विवरण मार्गदर्शन को दिशा देते हैं। वे सत्यापित BIS साक्ष्य नहीं हैं।', reportDisclaimer: 'यह सूचनात्मक मार्गदर्शन है, BIS लाइसेंस, प्रमाणपत्र, कानूनी राय या पूर्ण आधिकारिक आवेदन पैकेज नहीं।',
    evidenceNeedDetails: 'और विवरण चाहिए', evidenceInsufficient: 'साक्ष्य अपर्याप्त है', evidenceGrounded: 'साक्ष्य-आधारित उत्तर', journeyApplicable: 'लागू मानक', journeyWhy: 'ये मानक क्यों लागू होते हैं', journeyChecklist: 'आपकी अनुपालन जाँच सूची', journeyImportant: 'महत्वपूर्ण शर्तें', journeyNextAction: 'अनुशंसित अगला कदम', sourcesHeading: 'स्रोत', verifiedSources: 'सत्यापित स्रोत', viewVerifiedDetails: 'सत्यापित स्रोत विवरण देखें', referencedPages: '{document} में संदर्भित पृष्ठ', source: 'स्रोत', page: 'पृष्ठ', pages: 'पृष्ठ', pageUnavailable: 'उपलब्ध नहीं', viewEvidence: 'साक्ष्य देखें', extractedSourceText: 'निकाला गया स्रोत पाठ', openSourcePdf: 'स्रोत PDF खोलें', openSourcePdfAria: 'स्रोत PDF {filename}{page} खोलें', pdfOpenError: 'स्रोत PDF नहीं खोला जा सका। कृपया पुनः प्रयास करें।',
    printReportAria: 'अनुपालन पासपोर्ट', printReportTitle: 'अनुपालन पासपोर्ट', printReportSubtitle: 'साक्ष्य-आधारित सूचनात्मक मार्गदर्शन', generated: 'निर्मित', printProductProfile: 'उत्पाद प्रोफ़ाइल', printDetail: 'विवरण', printProvidedInformation: 'दी गई जानकारी', printWhy: 'यह क्यों लागू होता है', printChecklist: 'अनुपालन जाँच सूची', printImportant: 'महत्वपूर्ण शर्तें और सीमाएँ', printDocument: 'दस्तावेज़', printReferencedPages: 'संदर्भित पृष्ठ', printProfileNote: 'ये विवरण मार्गदर्शन को व्यक्तिगत बनाने के लिए उपयोगकर्ता ने दिए हैं। वे सत्यापित BIS साक्ष्य नहीं हैं।', printFooter: 'लागू आवश्यकताओं की पुष्टि BIS या योग्य विशेषज्ञ से करें।',
    passportTitle: 'अनुपालन पासपोर्ट', passportAvailable: 'साक्ष्य-समर्थित मार्गदर्शन उपलब्ध है', passportNeedsInformation: 'और जानकारी चाहिए', passportNeedsVerification: 'सत्यापन चाहिए', passportReportId: 'रिपोर्ट आईडी', passportGenerated: 'निर्मित', passportLanguage: 'चुनी गई भाषा', passportNotice: 'सूचनात्मक मार्गदर्शन — BIS प्रमाणपत्र नहीं।', passportProductProfile: 'उत्पाद प्रोफ़ाइल', passportUserProvided: 'उपयोगकर्ता द्वारा दी गई जानकारी — सत्यापित BIS साक्ष्य नहीं।', passportApplicable: 'लागू मानक', passportFindings: 'साक्ष्य-समर्थित पूर्ण निष्कर्ष', passportMissingProfile: 'अधूरी प्रोफ़ाइल जानकारी', passportVerificationNeeded: 'सत्यापन आवश्यक', passportNextActions: 'अगली तीन कार्रवाइयाँ', passportSources: 'उद्धृत साक्ष्य', passportEvidenceVerification: 'अंतिम उत्तर को अनुपालन निर्णय के लिए उपयोग करने से पहले सत्यापन चाहिए।', passportNoMissing: 'इस मार्गदर्शन में कोई अधूरा प्रोफ़ाइल फ़ील्ड नहीं पहचाना गया है।', passportNoVerification: 'इस मार्गदर्शन में कोई अतिरिक्त सत्यापन आवश्यकता नहीं पहचानी गई है।', passportNoActions: 'कोई साक्ष्य-समर्थित अगली कार्रवाई उपलब्ध नहीं है।', saveAsPdf: 'PDF के रूप में सहेजें / प्रिंट', saveAsPdfAria: 'अनुपालन पासपोर्ट को PDF के रूप में सहेजें या प्रिंट करें',
  },
  mr: {
    appTitle: 'बीआयएस एआय सहाय्यक', appSubtitle: 'अनुक्रमित BIS दस्तऐवजांमधून मानके आणि प्रमाणन मार्गदर्शन', languageLabel: 'भाषा',
    guidanceMode: 'मार्गदर्शन मोड', askQuestion: 'प्रश्न विचारा', complianceWizard: 'अनुपालन सहाय्यक',
    heroTitle: 'पुराव्यासह व्यावहारिक मानक मार्गदर्शन', heroDescription: 'अनुक्रमित BIS दस्तऐवजांवर आधारित AI-निर्मित माहितीपर मार्गदर्शन. अंतिम अनुपालन आवश्यकतांसाठी BIS किंवा पात्र तज्ज्ञाकडून पडताळणी करा.',
    footer: 'केवळ माहितीपर मार्गदर्शन. अंतिम अनुपालन आवश्यकतांची पडताळणी BIS किंवा पात्र तज्ज्ञाकडून करा.',
    audienceLabel: 'मी आहे:', audienceGeneral: 'सामान्य वापरकर्ता', audienceManufacturer: 'उत्पादक', audienceConsumer: 'ग्राहक',
    questionLabel: 'BIS खेळण्याच्या मानकांबद्दल प्रश्न विचारा', send: 'पाठवा', sending: 'पाठवत आहे…', suggestedQuestions: 'सुचवलेले प्रश्न', startOver: 'पुन्हा सुरू करा',
    statusReady: 'बॅकएंड तयार आहे', statusDegraded: 'बॅकएंड मर्यादित आहे', statusUnavailable: 'बॅकएंड उपलब्ध नाही', loading: 'BIS दस्तऐवज शोधले जात आहेत आणि संदर्भ पडताळले जात आहेत…', retry: 'पुन्हा प्रयत्न करा', updatingAnswers: 'उत्तरे अद्ययावत केली जात आहेत…',
    suggestionBattery: 'बॅटरीवर चालणाऱ्या खेळण्याला कोणते मानक लागू होते?', suggestionHandmade: 'सर्व हस्तनिर्मित खेळण्यांना सूट आहे का?', suggestionDocuments: 'नवीन खेळण्यांच्या मालिकेसाठी कोणती कागदपत्रे आवश्यक आहेत?', suggestionTransition: '2026 चा संक्रमण आदेश काय करतो?',
    roleManufacturer: 'उत्पादक', roleConsumer: 'ग्राहक', choiceNotSure: 'निश्चित नाही', choiceBattery: 'बॅटरीवर चालणारे', choiceMains: 'मुख्य वीजेवर चालणारे', choiceNonElectric: 'विद्युतविरहित', choiceUnder3: '3 वर्षांखालील', choice3to8: '3 ते 8', choiceOver8: '8 वर्षांवरील', choiceMultiple: 'एकापेक्षा जास्त वयोगट', choiceIdentifyStandards: 'लागू मानके ओळखा', choiceNewLicence: 'नवीन परवान्यासाठी अर्ज करा', choiceAddSeries: 'नवीन खेळण्यांची मालिका जोडा', choiceExemption: 'संभाव्य सूट तपासा', choiceTransition: 'संक्रमण आदेश समजून घ्या', choiceRoadmap: 'माझा अनुपालन आराखडा तयार करा', choiceResearching: 'माहिती गोळा करत आहे', choicePreparing: 'अर्ज तयार करत आहे', choiceLicensed: 'आधीच परवानाधारक', choiceScopeExtension: 'विद्यमान परवान्यात जोडत आहे',
    wizardEyebrow: 'मार्गदर्शित अनुपालन प्रवास', wizardEntryTitle: 'अनुपालन सहाय्यक', wizardEntryLead: 'तुमच्यासाठी योग्य मार्गदर्शनाने सुरुवात करा', wizardEntryDescription: 'उद्धृत BIS मार्गदर्शन मिळवण्यासाठी काही सोप्या प्रश्नांची उत्तरे द्या. गरज असल्यास तुम्ही निश्चित नाही निवडू शकता.', consumerCard: 'खरेदी किंवा उत्पादनाची तुलना करण्यापूर्वी खेळण्याची मानके समजून घ्या.', manufacturerCard: 'तुमच्या उत्पादनासाठी वैयक्तिक, पुरावा-आधारित अनुपालन मार्ग तयार करा.', recommendedJourney: 'शिफारस केलेला प्रवास',
    stepProduct: 'तुमचे उत्पादन', stepPower: 'वीज प्रकार', stepAge: 'अपेक्षित वयोगट', stepStage: 'सध्याचा टप्पा', stepNeed: 'तुम्हाला काय हवे आहे', helpProduct: 'खेळण्याचे साध्या शब्दांत वर्णन करा. यामुळे योग्य BIS सामग्री शोधण्यास मदत होते.', helpPower: 'खेळणे कसे चालते ते निवडा. माहिती नसल्यास निश्चित नाही निवडा.', helpAge: 'खेळणे कोणत्या वयोगटासाठी आहे ते निवडा. माहिती नसल्यास निश्चित नाही निवडा.', helpStage: 'तुम्ही प्रक्रियेत कुठे आहात ते सांगा. परवाना म्हणजे समाविष्ट उत्पादने बनवण्याची किंवा विकण्याची BIS परवानगी.', helpNeed: 'या छोट्या प्रवासातून तुम्हाला हवा असलेला परिणाम निवडा.', productDescription: 'उत्पादनाचे वर्णन किंवा प्रकार', validationProduct: '2 ते 300 वर्ण प्रविष्ट करा.', back: 'मागे', continue: 'पुढे जा', preparing: 'पुरावा-आधारित मार्गदर्शन तयार होत आहे…', generate: 'माझे मार्गदर्शन तयार करा', stepProgress: 'टप्पा {current} पैकी 5', journeyLabel: 'प्रवास', reviewAnswers: 'तयार करण्यापूर्वी उत्तरांचा आढावा घ्या', notAnswered: 'उत्तर दिलेले नाही', editProduct: 'उत्पादन संपादित करा', editPower: 'वीज प्रकार संपादित करा', editAge: 'वयोगट संपादित करा', editStage: 'सध्याचा टप्पा संपादित करा', editGoal: 'मार्गदर्शन उद्दिष्ट संपादित करा',
    clarificationEyebrow: 'आणखी एक तपशील', clarificationTitle: 'आम्हाला आणखी एक तपशील हवा आहे', clarificationDescription: 'उत्पादनाचा तपशील पुरेसा स्पष्ट होईपर्यंत आम्ही आराखडा तयार करणार नाही.', editThisAnswer: 'हे उत्तर संपादित करा', groundedGuidance: 'तुमचे पुरावा-आधारित मार्गदर्शन', journeyTitle: 'अनुपालन प्रवास', journeyResultAria: 'अनुपालन प्रवासाचा निकाल', journeyDescription: 'या मार्गदर्शनामागील पुराव्याचे पुनरावलोकन करण्यासाठी खालील सत्यापित स्रोत वापरा.', downloadPrint: 'डाउनलोड / प्रिंट अहवाल', downloadPrintAria: 'अनुपालन कृती अहवाल डाउनलोड किंवा प्रिंट करा', profileTitle: 'तुमची उत्पादन प्रोफाइल', profileProduct: 'उत्पादन', profilePower: 'वीज प्रकार', profileAge: 'अपेक्षित वयोगट', profileStage: 'सध्याचा टप्पा', profileGoal: 'मार्गदर्शन उद्दिष्ट', profileNote: 'वापरकर्त्याने दिलेले तपशील मार्गदर्शनाला दिशा देतात. ते सत्यापित BIS पुरावे नाहीत.', reportDisclaimer: 'हे माहितीपर मार्गदर्शन आहे; BIS परवाना, प्रमाणपत्र, कायदेशीर मत किंवा पूर्ण अधिकृत अर्ज पॅकेज नाही.',
    evidenceNeedDetails: 'अधिक तपशील हवेत', evidenceInsufficient: 'पुरावा अपुरा आहे', evidenceGrounded: 'पुरावा-आधारित उत्तर', journeyApplicable: 'लागू मानके', journeyWhy: 'ही मानके का लागू होतात', journeyChecklist: 'तुमची अनुपालन तपासणी सूची', journeyImportant: 'महत्त्वाच्या अटी', journeyNextAction: 'शिफारस केलेली पुढील कृती', sourcesHeading: 'स्रोत', verifiedSources: 'सत्यापित स्रोत', viewVerifiedDetails: 'सत्यापित स्रोत तपशील पहा', referencedPages: '{document} मधील संदर्भित पाने', source: 'स्रोत', page: 'पान', pages: 'पाने', pageUnavailable: 'उपलब्ध नाही', viewEvidence: 'पुरावा पहा', extractedSourceText: 'काढलेला स्रोत मजकूर', openSourcePdf: 'स्रोत PDF उघडा', openSourcePdfAria: 'स्रोत PDF {filename}{page} उघडा', pdfOpenError: 'स्रोत PDF उघडता आला नाही. कृपया पुन्हा प्रयत्न करा.',
    printReportAria: 'अनुपालन पासपोर्ट', printReportTitle: 'अनुपालन पासपोर्ट', printReportSubtitle: 'पुरावा-आधारित माहितीपर मार्गदर्शन', generated: 'तयार केले', printProductProfile: 'उत्पादन प्रोफाइल', printDetail: 'तपशील', printProvidedInformation: 'दिलेली माहिती', printWhy: 'हे का लागू होते', printChecklist: 'अनुपालन तपासणी सूची', printImportant: 'महत्त्वाच्या अटी आणि मर्यादा', printDocument: 'दस्तऐवज', printReferencedPages: 'संदर्भित पाने', printProfileNote: 'हे तपशील मार्गदर्शन वैयक्तिक करण्यासाठी वापरकर्त्याने दिले आहेत. ते सत्यापित BIS पुरावे नाहीत.', printFooter: 'लागू आवश्यकतांची पडताळणी BIS किंवा पात्र तज्ज्ञाकडून करा।',
    passportTitle: 'अनुपालन पासपोर्ट', passportAvailable: 'पुरावा-आधारित मार्गदर्शन उपलब्ध आहे', passportNeedsInformation: 'अधिक माहिती हवी आहे', passportNeedsVerification: 'पडताळणी आवश्यक आहे', passportReportId: 'अहवाल आयडी', passportGenerated: 'तयार केले', passportLanguage: 'निवडलेली भाषा', passportNotice: 'माहितीपर मार्गदर्शन — BIS प्रमाणपत्र नाही.', passportProductProfile: 'उत्पादन प्रोफाइल', passportUserProvided: 'वापरकर्त्याने दिलेली माहिती — सत्यापित BIS पुरावा नाही.', passportApplicable: 'लागू मानके', passportFindings: 'पुरावा-आधारित पूर्ण निष्कर्ष', passportMissingProfile: 'गहाळ प्रोफाइल माहिती', passportVerificationNeeded: 'पडताळणी आवश्यक', passportNextActions: 'पुढील तीन कृती', passportSources: 'उद्धृत पुरावा', passportEvidenceVerification: 'अंतिम उत्तरावर अनुपालन निर्णयासाठी अवलंबून राहण्यापूर्वी पडताळणी आवश्यक आहे.', passportNoMissing: 'या मार्गदर्शनात कोणतेही अपूर्ण प्रोफाइल क्षेत्र ओळखलेले नाही.', passportNoVerification: 'या मार्गदर्शनात कोणतीही अतिरिक्त पडताळणी आवश्यकता ओळखलेली नाही.', passportNoActions: 'कोणतीही पुरावा-आधारित पुढील कृती उपलब्ध नाही.', saveAsPdf: 'PDF म्हणून जतन करा / प्रिंट', saveAsPdfAria: 'अनुपालन पासपोर्ट PDF म्हणून जतन करा किंवा प्रिंट करा',
  },
} as const;

export type Language = keyof typeof translations;
export type TranslationKey = keyof typeof translations.en;
export const languageNames: Record<Language, string> = { en: 'English', hi: 'हिन्दी', mr: 'मराठी' };

export const profileLabelKeys = {
  manufacturer: 'roleManufacturer', consumer: 'roleConsumer', not_sure: 'choiceNotSure', battery_operated: 'choiceBattery', mains_electric: 'choiceMains', non_electric: 'choiceNonElectric', under_3: 'choiceUnder3', '3_to_8': 'choice3to8', over_8: 'choiceOver8', multiple: 'choiceMultiple', identify_standards: 'choiceIdentifyStandards', new_licence: 'choiceNewLicence', add_new_series: 'choiceAddSeries', check_exemption: 'choiceExemption', understand_transition: 'choiceTransition', complete_roadmap: 'choiceRoadmap', researching: 'choiceResearching', preparing_application: 'choicePreparing', existing_licence: 'choiceLicensed', scope_extension: 'choiceScopeExtension',
} as const satisfies Record<string, TranslationKey>;

export function isLanguage(value: unknown): value is Language {
  return typeof value === 'string' && value in translations;
}
